version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
        prefix: ".github"