# .sops.yaml

keys:
  - &users:
    - &administrator age1fkurz06svzey276q7r68amvc0f7h0lfrvmpjvm8n0tzy6tpazgqsfmhd65
  - &hosts:
    - &frametop
    - &woody age1sfg83rldxqkcyygl42nuk3r5v6yj2492s6dtxy22ej3x7t8t65dq0pal93
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *administrator
      - *frametop
      - *woody
