# .sops.yaml

keys:
  - &administrator {{YOUR KEY HERE}}
  - &frametop {{YOUR KEY HERE}}
creation_rules:
  - path_regex: hosts/common/[^/]+\.yaml$
    key_groups:
    - age:
      - *administrator
      - *frametop
  - path_regex: hosts/common/users/[^/]+\.yaml$
    key_groups:
    - age:
      - *administrator
      - *frametop
  - path_regex: hosts/frametop/[^/]+\.yaml$
    key_groups:
    - age:
      - *administrator
      - *frametop
