# .sops.yaml

keys:
  - &administrator 93559682B3387BC2367FCB71436A329380CD5059
  - &frametop age1jny3l6sy32vss49rj32qvszpctmjtgl9hdksqvh826ekx6c2e5aqns6dcm
  - &woody age1jny3l6sy32vss49rj32qvszpctmjtgl9hdksqvh826ekx6c2e5aqns6dcm
creation_rules:
  - path_regex: hosts/common/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *administrator
    - age:
      - *frametop
      - *woody
  - path_regex: hosts/frametop/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *administrator
    - age:
      - *frametop
  - path_regex: hosts/woody/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *administrator
    - age:
      - *woody

