{
  config,
  pkgs,
  lib,
  ...
}:

let
  claudeHome = "${config.home.homeDirectory}/.claude";
  settingsPath = "${claudeHome}/settings.json";
  generateClaudeConfigScript = pkgs.writeShellApplication {
    name = "generate-claude-config";
    runtimeInputs = with pkgs; [
      coreutils
      jq
    ];
    text = ''
      set -euo pipefail

      # Check if secrets exist
      if [ ! -f "${config.sops.secrets.context7-token.path}" ]; then
        echo "Error: context7-token secret not found at ${config.sops.secrets.context7-token.path}" >&2
        exit 1
      fi

      if [ ! -f "${config.sops.secrets.github-pat.path}" ]; then
        echo "Error: github-pat secret not found at ${config.sops.secrets.github-pat.path}" >&2
        exit 1
      fi

      # Read secrets
      CONTEXT7_TOKEN=$(cat "${config.sops.secrets.context7-token.path}")
      GITHUB_PERSONAL_ACCESS_TOKEN=$(cat "${config.sops.secrets.github-pat.path}")

      # Generate the .env file with actual values
      cat > "${claudeHome}/.env" << EOF
      # MCP Server Environment Variables
      # Generated by systemd service: generate-claude-config
      CONTEXT7_TOKEN=$CONTEXT7_TOKEN
      GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_PERSONAL_ACCESS_TOKEN
      EOF
      chmod 600 "${claudeHome}/.env"
      echo "Generated ${claudeHome}/.env file"

      # Process mcp-servers.json to inject actual token values
      # Replace CONTEXT7_TOKEN and GITHUB_PERSONAL_ACCESS_TOKEN placeholders with actual values
      SOURCE_MCP="${claudeHome}/mcp-servers.json"
      PROCESSED_MCP="${claudeHome}/mcp-servers-processed.json"

      if [ -f "$SOURCE_MCP" ]; then
        # Use jq to inject actual token values
        jq \
          --arg context7_token "$CONTEXT7_TOKEN" \
          --arg github_token "$GITHUB_PERSONAL_ACCESS_TOKEN" \
          '.context7.env.CONTEXT7_TOKEN = $context7_token |
           .github.env.GITHUB_PERSONAL_ACCESS_TOKEN = $github_token' \
          "$SOURCE_MCP" > "$PROCESSED_MCP"

        chmod 600 "$PROCESSED_MCP"
        echo "Generated processed MCP config at $PROCESSED_MCP"
      else
        echo "Warning: Source MCP config not found at $SOURCE_MCP" >&2
      fi
    '';
  };
in
{
  # Status line script for Claude Code
  home.file."${claudeHome}/statusline.sh" = {
    source = ./statusline.sh;
    executable = true;
  };

  # Format hook script for Python and TypeScript
  home.file."${claudeHome}/format-hook.sh" = {
    source = ./format-hook.sh;
    executable = true;
  };

  # Security hook: Block dangerous commands and protect sensitive files
  home.file."${claudeHome}/security-hook.sh" = {
    source = ./security-hook.sh;
    executable = true;
  };

  # Linting hook: Run linters after code changes
  home.file."${claudeHome}/lint-hook.sh" = {
    source = ./lint-hook.sh;
    executable = true;
  };

  # Type checking hook: Run type checkers after code changes
  home.file."${claudeHome}/typecheck-hook.sh" = {
    source = ./typecheck-hook.sh;
    executable = true;
  };

  # Notification hook: Desktop notifications when Claude needs attention
  home.file."${claudeHome}/notification-hook.sh" = {
    source = ./notification-hook.sh;
    executable = true;
  };

  # Git safety hook: Prevent dangerous git operations
  home.file."${claudeHome}/git-safety-hook.sh" = {
    source = ./git-safety-hook.sh;
    executable = true;
  };

  # Configuration Documentation Files
  # These files are reference documentation for Claude Code workflows, modes, and MCP servers.
  # They are automatically loaded via Cursor rules (.cursor/rules/claude-*.mdc) and should
  # be referenced when relevant. See .cursor/rules/claude-config.mdc for usage guidelines.

  # Core behavioral and project documentation
  home.file."${claudeHome}/BUSINESS_SYMBOLS.md" = {
    source = ./config/BUSINESS_SYMBOLS.md;
  };
  home.file."${claudeHome}/FLAGS.md" = {
    source = ./config/FLAGS.md;
  };
  home.file."${claudeHome}/KNOWLEDGE.md" = {
    source = ./config/KNOWLEDGE.md;
  };
  home.file."${claudeHome}/PLANNING.md" = {
    source = ./config/PLANNING.md;
  };
  home.file."${claudeHome}/PRINCIPLES.md" = {
    source = ./config/PRINCIPLES.md;
  };
  home.file."${claudeHome}/RESEARCH_CONFIG.md" = {
    source = ./config/RESEARCH_CONFIG.md;
  };
  home.file."${claudeHome}/RULES.md" = {
    source = ./config/RULES.md;
  };
  home.file."${claudeHome}/TASK.md" = {
    source = ./config/TASK.md;
  };

  # MODES
  home.file."${claudeHome}/MODE_Brainstorming.md" = {
    source = ./config/MODE_Brainstorming.md;
  };
  home.file."${claudeHome}/MODE_Business_Panel.md" = {
    source = ./config/MODE_Business_Panel.md;
  };
  home.file."${claudeHome}/MODE_DeepResearch.md" = {
    source = ./config/MODE_DeepResearch.md;
  };
  home.file."${claudeHome}/MODE_Introspection.md" = {
    source = ./config/MODE_Introspection.md;
  };
  home.file."${claudeHome}/MODE_Orchestration.md" = {
    source = ./config/MODE_Orchestration.md;
  };
  home.file."${claudeHome}/MODE_Task_Management.md" = {
    source = ./config/MODE_Task_Management.md;
  };
  home.file."${claudeHome}/MODE_Token_Efficiency.md" = {
    source = ./config/MODE_Token_Efficiency.md;
  };

  # MCP SERVERS
  home.file."${claudeHome}/MCP_SERVERS.md" = {
    source = ./config/MCP_SERVERS.md;
  };
  home.file."${claudeHome}/MCP_Context7.md" = {
    source = ./config/MCP_Context7.md;
  };
  home.file."${claudeHome}/MCP_Playwright.md" = {
    source = ./config/MCP_Playwright.md;
  };
  home.file."${claudeHome}/MCP_Sequential.md" = {
    source = ./config/MCP_Sequential.md;
  };
  home.file."${claudeHome}/MCP_Serena.md" = {
    source = ./config/MCP_Serena.md;
  };
  home.file."${claudeHome}/MCP_Context7_SETUP.md" = {
    source = ./config/MCP_Context7_SETUP.md;
  };

  # COMMANDS
  home.file."${claudeHome}/commands/sc/analyze.md" = {
    source = ./config/commands/sc/analyze.md;
  };
  home.file."${claudeHome}/commands/sc/brainstorm.md" = {
    source = ./config/commands/sc/brainstorm.md;
  };
  home.file."${claudeHome}/commands/sc/build.md" = {
    source = ./config/commands/sc/build.md;
  };
  home.file."${claudeHome}/commands/sc/business-panel.md" = {
    source = ./config/commands/sc/business-panel.md;
  };
  home.file."${claudeHome}/commands/sc/design.md" = {
    source = ./config/commands/sc/design.md;
  };
  home.file."${claudeHome}/commands/sc/document.md" = {
    source = ./config/commands/sc/document.md;
  };
  home.file."${claudeHome}/commands/sc/estimate.md" = {
    source = ./config/commands/sc/estimate.md;
  };
  home.file."${claudeHome}/commands/sc/explain.md" = {
    source = ./config/commands/sc/explain.md;
  };
  home.file."${claudeHome}/commands/sc/git.md" = {
    source = ./config/commands/sc/git.md;
  };
  home.file."${claudeHome}/commands/sc/help.md" = {
    source = ./config/commands/sc/help.md;
  };
  home.file."${claudeHome}/commands/sc/implement.md" = {
    source = ./config/commands/sc/implement.md;
  };
  home.file."${claudeHome}/commands/sc/improve.md" = {
    source = ./config/commands/sc/improve.md;
  };
  home.file."${claudeHome}/commands/sc/index.md" = {
    source = ./config/commands/sc/index.md;
  };
  home.file."${claudeHome}/commands/sc/load.md" = {
    source = ./config/commands/sc/load.md;
  };
  home.file."${claudeHome}/commands/sc/reflect.md" = {
    source = ./config/commands/sc/reflect.md;
  };
  home.file."${claudeHome}/commands/sc/research.md" = {
    source = ./config/commands/sc/research.md;
  };
  home.file."${claudeHome}/commands/sc/save.md" = {
    source = ./config/commands/sc/save.md;
  };
  home.file."${claudeHome}/commands/sc/spawn.md" = {
    source = ./config/commands/sc/spawn.md;
  };
  home.file."${claudeHome}/commands/sc/spec-panel.md" = {
    source = ./config/commands/sc/spec-panel.md;
  };
  home.file."${claudeHome}/commands/sc/task.md" = {
    source = ./config/commands/sc/task.md;
  };
  home.file."${claudeHome}/commands/sc/test.md" = {
    source = ./config/commands/sc/test.md;
  };
  home.file."${claudeHome}/commands/sc/troubleshoot.md" = {
    source = ./config/commands/sc/troubleshoot.md;
  };
  home.file."${claudeHome}/commands/sc/workflow.md" = {
    source = ./config/commands/sc/workflow.md;
  };

  programs.claude-code = {
    enable = true;
    package = pkgs.claude-code;

    settings = {
      env = {
        DISABLE_TELEMETRY = "1";
        USE_BUILTIN_RIPGREP = "0"; # prefer system rg
      };

      # Permissions (deny sensitive files; allow/ask examples)
      permissions = {
        allow = [
          "*"
        ];
      };

      # Hooks: run before/after tool use
      hooks = {
        PreToolUse = [
          # Security: Block dangerous commands and protect sensitive files
          {
            matcher = "Bash|Edit|Write";
            hooks = [
              {
                type = "command";
                command = "${claudeHome}/security-hook.sh";
              }
            ];
          }
          # Git safety: Prevent dangerous git operations
          {
            matcher = "Bash";
            hooks = [
              {
                type = "command";
                command = "${claudeHome}/git-safety-hook.sh";
              }
            ];
          }
          {
            matcher = "Bash";
            hooks = [
              {
                type = "command";
                command = "echo 'Running tool…' >&2";
              }
            ];
          }
        ];
        PostToolUse = [
          {
            matcher = "Bash";
            hooks = [
              {
                type = "command";
                command = "echo 'Tool done.' >&2";
              }
            ];
          }
          # Format Python and TypeScript files after writes
          {
            matcher = "Edit|Write";
            hooks = [
              {
                type = "command";
                command = "${claudeHome}/format-hook.sh";
                async = true;
              }
              # Lint code after formatting
              {
                type = "command";
                command = "${claudeHome}/lint-hook.sh";
                async = true;
              }
              # Type check after changes
              {
                type = "command";
                command = "${claudeHome}/typecheck-hook.sh";
                async = true;
              }
            ];
          }
        ];
        Notification = [
          # Desktop notifications when Claude needs attention
          {
            matcher = "";
            hooks = [
              {
                type = "command";
                command = "${claudeHome}/notification-hook.sh";
                async = true;
              }
            ];
          }
        ];
      };

      outputStyle = "Explanatory";

      statusLine = {
        type = "command";
        command = "${claudeHome}/statusline.sh";
        padding = 0; # Optional: set to 0 to let status line go to
      };
      forceLoginMethod = "console";

      # Session management
      cleanupPeriodDays = 60;
      showTurnDuration = true;

      # Example memory settings (user-level)
      memory = {
        enabled = true;
        dir = "${config.home.homeDirectory}/.local/share/claude-code/memory";
        scope = "per-project";
        maxItems = 500;
      };

    };

    # MCP servers configuration - will be processed at runtime to inject SOPS secrets
    # The actual token injection happens via the systemd service below
    mcpServers = builtins.fromJSON (builtins.readFile ./mcp-servers.json);

    # Import agents from the agents/ directory
    agents = {
      ai-engineer = (builtins.readFile ./config/agents/ai-engineer.md);
      # architect-review = (builtins.readFile ./config/agents/architect-review.md);
      code-reviewer = (builtins.readFile ./config/agents/code-reviewer.md);
      debugger = (builtins.readFile ./config/agents/debugger.md);
      # docs-architect = (builtins.readFile ./config/agents/docs-architect.md);
      # mermaid-expert = (builtins.readFile ./config/agents/mermaid-expert.md);
      nix-systems-specialist = (builtins.readFile ./config/agents/nix-systems-specialist.md);
      # rust-pro = (builtins.readFile ./config/agents/rust-pro.md);
      # sql-pro = (builtins.readFile ./config/agents/sql-pro.md);
      # test-automator = (builtins.readFile ./config/agents/test-automator.md);
      # typescript-pro = (builtins.readFile ./config/agents/typescript-pro.md);
      backend-architect = (builtins.readFile ./config/agents/backend-architect.md);
      business-panel = (builtins.readFile ./config/agents/business-panel-experts.md);
      deep-research-agent = (builtins.readFile ./config/agents/deep-research-agent.md);
      devops-architect = (builtins.readFile ./config/agents/devops-architect.md);
      frontend-architect = (builtins.readFile ./config/agents/frontend-architect.md);
      learning-guide = (builtins.readFile ./config/agents/learning-guide.md);
      performance-engineer = (builtins.readFile ./config/agents/performance-engineer.md);
      python-pro = (builtins.readFile ./config/agents/python-pro.md);
      refactoring-expert = (builtins.readFile ./config/agents/refactoring-expert.md);
      requirements-analyst = (builtins.readFile ./config/agents/requirements-analyst.md);
      security-engineer = (builtins.readFile ./config/agents/security-engineer.md);
      socratic-mentor = (builtins.readFile ./config/agents/socratic-mentor.md);
      system-architect = (builtins.readFile ./config/agents/system-architect.md);
      test-automator = (builtins.readFile ./config/agents/test-automator.md);
      docs-architect = (builtins.readFile ./config/agents/docs-architect.md);
    };

  };

  # Note: .env file is generated at runtime by the generate-claude-config systemd service
  # This ensures SOPS secrets are available when the file is created

  # Create a systemd user service to generate .env file and process mcp-servers.json after SOPS secrets are available
  systemd.user.services.generate-claude-config = {
    Unit = {
      Description = "Generate Claude Code configuration files with SOPS secrets";
      After = [ "sops-nix.service" ];
      Wants = [ "sops-nix.service" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${generateClaudeConfigScript}/bin/generate-claude-config";
      RemainAfterExit = true;
    };
    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  # Create a wrapper script that ensures environment variables are set when Claude Code starts
  home.file."${claudeHome}/claude-code-wrapper.sh" = {
    text = ''
      #!/usr/bin/env bash
      # Wrapper script to ensure CONTEXT7_TOKEN is available when Claude Code starts

      # Load environment variables from .env file if it exists
      if [ -f "${claudeHome}/.env" ]; then
        set -a
        source "${claudeHome}/.env"
        set +a
      fi

      # Use processed MCP config if available, otherwise fall back to original
      if [ -f "${claudeHome}/mcp-servers-processed.json" ]; then
        export MCP_SERVERS_CONFIG="${claudeHome}/mcp-servers-processed.json"
      fi

      # Launch Claude Code with environment variables
      exec ${pkgs.claude-code}/bin/claude-code "$@"
    '';
    executable = true;
  };
}
