.pragma library

// Static emoji catalog for the launcher emoji mode.
// Replaces the qs-emoji shell script — no Process spawn needed.
var emojis = [
    { name: "😀", title: "Grinning Face" },
    { name: "😃", title: "Grinning Face with Big Eyes" },
    { name: "😄", title: "Grinning Face with Smiling Eyes" },
    { name: "😁", title: "Beaming Face with Smiling Eyes" },
    { name: "😆", title: "Grinning Squinting Face" },
    { name: "😅", title: "Grinning Face with Sweat" },
    { name: "🤣", title: "Rolling on the Floor Laughing" },
    { name: "😂", title: "Face with Tears of Joy" },
    { name: "🙂", title: "Slightly Smiling Face" },
    { name: "🙃", title: "Upside-Down Face" },
    { name: "😉", title: "Winking Face" },
    { name: "😊", title: "Smiling Face with Smiling Eyes" },
    { name: "😇", title: "Smiling Face with Halo" },
    { name: "🥰", title: "Smiling Face with Hearts" },
    { name: "😍", title: "Smiling Face with Heart-Eyes" },
    { name: "🤩", title: "Star-Struck" },
    { name: "😘", title: "Face Blowing a Kiss" },
    { name: "😗", title: "Kissing Face" },
    { name: "☺️", title: "Smiling Face" },
    { name: "😚", title: "Kissing Face with Closed Eyes" },
    { name: "😙", title: "Kissing Face with Smiling Eyes" },
    { name: "😋", title: "Face Savoring Food" },
    { name: "😛", title: "Face with Tongue" },
    { name: "😜", title: "Winking Face with Tongue" },
    { name: "🤪", title: "Zany Face" },
    { name: "😝", title: "Squinting Face with Tongue" },
    { name: "🤑", title: "Money-Mouth Face" },
    { name: "🤗", title: "Hugging Face" },
    { name: "🤭", title: "Face with Hand Over Mouth" },
    { name: "🤫", title: "Shushing Face" },
    { name: "🤔", title: "Thinking Face" },
    { name: "🤐", title: "Zipper-Mouth Face" },
    { name: "🤨", title: "Face with Raised Eyebrow" },
    { name: "😐", title: "Neutral Face" },
    { name: "😑", title: "Expressionless Face" },
    { name: "😶", title: "Face Without Mouth" },
    { name: "😏", title: "Smirking Face" },
    { name: "😒", title: "Unamused Face" },
    { name: "🙄", title: "Face with Rolling Eyes" },
    { name: "😬", title: "Grimacing Face" },
    { name: "🤥", title: "Lying Face" },
    { name: "😌", title: "Relieved Face" },
    { name: "😔", title: "Pensive Face" },
    { name: "😪", title: "Sleepy Face" },
    { name: "🤤", title: "Drooling Face" },
    { name: "😴", title: "Sleeping Face" },
    { name: "😷", title: "Face with Medical Mask" },
    { name: "🤒", title: "Face with Temperature" },
    { name: "🤕", title: "Face with Head-Bandage" },
    { name: "🤢", title: "Nauseated Face" },
    { name: "🤮", title: "Face Vomiting" },
    { name: "🤧", title: "Sneezing Face" },
    { name: "🥵", title: "Hot Face" },
    { name: "🥶", title: "Cold Face" },
    { name: "🥴", title: "Woozy Face" },
    { name: "😵", title: "Dizzy Face" },
    { name: "🤯", title: "Exploding Head" },
    { name: "🤠", title: "Cowboy Hat Face" },
    { name: "🥳", title: "Partying Face" },
    { name: "😎", title: "Smiling Face with Sunglasses" },
    { name: "🤓", title: "Nerd Face" },
    { name: "🧐", title: "Face with Monocle" },
    { name: "😕", title: "Confused Face" },
    { name: "😟", title: "Worried Face" },
    { name: "🙁", title: "Slightly Frowning Face" },
    { name: "☹️", title: "Frowning Face" },
    { name: "😮", title: "Face with Open Mouth" },
    { name: "😯", title: "Hushed Face" },
    { name: "😲", title: "Astonished Face" },
    { name: "😳", title: "Flushed Face" },
    { name: "🥺", title: "Pleading Face" },
    { name: "😦", title: "Frowning Face with Open Mouth" },
    { name: "😧", title: "Anguished Face" },
    { name: "😨", title: "Fearful Face" },
    { name: "😰", title: "Anxious Face with Sweat" },
    { name: "😥", title: "Sad but Relieved Face" },
    { name: "😢", title: "Crying Face" },
    { name: "😭", title: "Loudly Crying Face" },
    { name: "😱", title: "Face Screaming in Fear" },
    { name: "😖", title: "Confounded Face" },
    { name: "😣", title: "Persevering Face" },
    { name: "😞", title: "Disappointed Face" },
    { name: "😓", title: "Downcast Face with Sweat" },
    { name: "😩", title: "Weary Face" },
    { name: "😫", title: "Tired Face" },
    { name: "🥱", title: "Yawning Face" },
    { name: "😤", title: "Face with Steam From Nose" },
    { name: "😡", title: "Pouting Face" },
    { name: "😠", title: "Angry Face" },
    { name: "🤬", title: "Face with Symbols on Mouth" },
    { name: "😈", title: "Smiling Face with Horns" },
    { name: "👿", title: "Angry Face with Horns" },
    { name: "💀", title: "Skull" },
    { name: "☠️", title: "Skull and Crossbones" },
    { name: "💩", title: "Pile of Poop" },
    { name: "🤡", title: "Clown Face" },
    { name: "👹", title: "Ogre" },
    { name: "👺", title: "Goblin" },
    { name: "👻", title: "Ghost" },
    { name: "👽", title: "Alien" },
    { name: "👾", title: "Alien Monster" },
    { name: "🤖", title: "Robot" },
    { name: "😺", title: "Grinning Cat" },
    { name: "😸", title: "Grinning Cat with Smiling Eyes" },
    { name: "😻", title: "Smiling Cat with Heart-Eyes" },
    { name: "😼", title: "Cat with Wry Smile" },
    { name: "😽", title: "Kissing Cat" },
    { name: "🙀", title: "Weary Cat" },
    { name: "😿", title: "Crying Cat" },
    { name: "😾", title: "Pouting Cat" },
    { name: "👋", title: "Waving Hand" },
    { name: "🤚", title: "Raised Back of Hand" },
    { name: "🖐️", title: "Hand with Fingers Splayed" },
    { name: "✋", title: "Raised Hand" },
    { name: "🖖", title: "Vulcan Salute" },
    { name: "👌", title: "OK Hand" },
    { name: "🤏", title: "Pinching Hand" },
    { name: "✌️", title: "Victory Hand" },
    { name: "🤞", title: "Crossed Fingers" },
    { name: "🤟", title: "Love-You Gesture" },
    { name: "🤘", title: "Sign of the Horns" },
    { name: "🤙", title: "Call Me Hand" },
    { name: "👈", title: "Backhand Index Pointing Left" },
    { name: "👉", title: "Backhand Index Pointing Right" },
    { name: "👆", title: "Backhand Index Pointing Up" },
    { name: "🖕", title: "Middle Finger" },
    { name: "👇", title: "Backhand Index Pointing Down" },
    { name: "☝️", title: "Index Pointing Up" },
    { name: "👍", title: "Thumbs Up" },
    { name: "👎", title: "Thumbs Down" },
    { name: "✊", title: "Raised Fist" },
    { name: "👊", title: "Oncoming Fist" },
    { name: "🤛", title: "Left-Facing Fist" },
    { name: "🤜", title: "Right-Facing Fist" },
    { name: "👏", title: "Clapping Hands" },
    { name: "🙌", title: "Raising Hands" },
    { name: "👐", title: "Open Hands" },
    { name: "🤲", title: "Palms Up Together" },
    { name: "🤝", title: "Handshake" },
    { name: "🙏", title: "Folded Hands" },
    { name: "✍️", title: "Writing Hand" },
    { name: "💅", title: "Nail Polish" },
    { name: "🤳", title: "Selfie" },
    { name: "💪", title: "Flexed Biceps" },
    { name: "🦾", title: "Mechanical Arm" },
    { name: "🦿", title: "Mechanical Leg" },
    { name: "🦵", title: "Leg" },
    { name: "🦶", title: "Foot" },
    { name: "👂", title: "Ear" },
    { name: "🦻", title: "Ear with Hearing Aid" },
    { name: "👃", title: "Nose" },
    { name: "🧠", title: "Brain" },
    { name: "🦷", title: "Tooth" },
    { name: "🦴", title: "Bone" },
    { name: "👀", title: "Eyes" },
    { name: "👁️", title: "Eye" },
    { name: "👅", title: "Tongue" },
    { name: "👄", title: "Mouth" },
    { name: "💋", title: "Kiss Mark" },
    { name: "🩸", title: "Drop of Blood" },
    { name: "✨", title: "Sparkles" },
    { name: "⭐", title: "Star" },
    { name: "🌟", title: "Glowing Star" },
    { name: "🔥", title: "Fire" },
    { name: "💥", title: "Collision" },
    { name: "💨", title: "Dash Away" },
    { name: "💦", title: "Sweat Drops" },
    { name: "❤️", title: "Red Heart" },
    { name: "🧡", title: "Orange Heart" },
    { name: "💛", title: "Yellow Heart" },
    { name: "💚", title: "Green Heart" },
    { name: "💙", title: "Blue Heart" },
    { name: "💜", title: "Purple Heart" },
    { name: "🖤", title: "Black Heart" },
    { name: "🤍", title: "White Heart" },
    { name: "🤎", title: "Brown Heart" },
    { name: "💔", title: "Broken Heart" },
    { name: "❣️", title: "Heart Exclamation" },
    { name: "💕", title: "Two Hearts" },
    { name: "💞", title: "Revolving Hearts" },
    { name: "💓", title: "Beating Heart" },
    { name: "💗", title: "Growing Heart" },
    { name: "💖", title: "Sparkling Heart" },
    { name: "💘", title: "Heart with Arrow" },
    { name: "💝", title: "Heart with Ribbon" },
    { name: "💟", title: "Heart Decoration" }
];
