#!/usr/bin/env bash

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Change to the script's directory
cd "$SCRIPT_DIR" || exit 1

nvfetcher || exit 1

# Path to the extensions file (relative to script directory, then to project root)
EXTENSIONS_FILE="../../home/features/vscode/marketplace-extensions.nix"

# Generate Nix list format from JSON
# Extract extensions with passthru (VS Code marketplace extensions)
extensions_json=$(jq -r '.[] | select(.passthru != null) | "\(.passthru.name)|\(.passthru.publisher)|\(.src.sha256)|\(.version)"' _sources/generated.json)

# Count extensions for comma handling
extension_count=$(echo "$extensions_json" | wc -l)

# Start building the Nix file
{
  echo "# This file is auto-generated by scripts/vscode/vscodefetch.sh"
  echo "# Do not edit manually - run the script to update extensions"
  echo ""
  echo "["

  # Process each extension
  current=0
  while IFS='|' read -r name publisher sha256 version; do
    current=$((current + 1))
    echo "  {"
    echo "    name = \"$name\";"
    echo "    publisher = \"$publisher\";"
    echo "    sha256 = \"$sha256\";"
    echo "    version = \"$version\";"
    if [ $current -lt $extension_count ]; then
      echo "  },"
    else
      echo "  }"
    fi
  done <<< "$extensions_json"

  echo "]"
} > "$EXTENSIONS_FILE"

echo "Generated $EXTENSIONS_FILE"
echo ""
echo "Extensions updated. Review the file and rebuild your NixOS configuration."

# Also keep the old format for reference (optional)
result=$(jq '.[] | select(.passthru != null) | {name: .passthru.name, publisher: .passthru.publisher, sha256: .src.sha256, version: .version}' _sources/generated.json)
formatted_result=$(echo "$result" | sed -e 's/"name"/name/' -e 's/"publisher"/publisher/' -e 's/"sha256"/sha256/' -e 's/"version"/version/' -e 's/: / = /g' -e 's/,/;/g')
formatted_result=$(echo "$formatted_result" | sed -e 's/\([^;]\)"$/\1";/')
echo "$formatted_result" > generated-vscode-nix.txt

