pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "."

// Exports active color palette to well-known files after each color change.
// Enables downstream tools (ghostty, kitty, scripts, CSS generators) to pick
// up the current shell colors. Opt-in via Config.colorExportEnabled.
//
// Exports:
//   ~/.local/state/quickshell/colors-export.json  (machine-readable)
//   ~/.local/state/quickshell/colors-export.sh    (sourceable shell vars)
//
// Terminal integrations:
//   Ghostty: writes ghostty-colors config fragment (auto-reloaded via config-file include)
//   Kitty:   sends colors via kitty @ set-colors remote control
//
// Also fires HookService "colors-changed" with the JSON path.
QtObject {
    id: root

    readonly property string _stateDir: Quickshell.statePath("")
    readonly property string jsonPath: _stateDir + "colors-export.json"
    readonly property string shellPath: _stateDir + "colors-export.sh"
    readonly property string ghosttyPath: _stateDir + "ghostty-colors"

    // Debounce: wait for color transition to finish before exporting
    property bool _pendingExport: false

    property Connections _colorConn: Connections {
        target: Colors
        function onIsTransitioningChanged() {
            if (!Colors.isTransitioning && root._pendingExport) {
                root._pendingExport = false;
                root._doExport();
            }
        }
        function onBackgroundChanged() { root._scheduleExport(); }
        function onPrimaryChanged()    { root._scheduleExport(); }
        function onTextChanged()       { root._scheduleExport(); }
    }

    function _scheduleExport() {
        if (!Config.colorExportEnabled) return;
        if (Colors.isTransitioning || Colors.skipTransition) {
            root._pendingExport = true;
            return;
        }
        _exportTimer.restart();
    }

    property Timer _exportTimer: Timer {
        interval: 200
        onTriggered: root._doExport()
    }

    function _colorHex(c) {
        return Colors.withAlpha(c, 1.0).toString();
    }

    function _doExport() {
        if (!Config.colorExportEnabled) return;

        var palette = {
            background:    _colorHex(Colors.background),
            surface:       _colorHex(Colors.surface),
            primary:       _colorHex(Colors.primary),
            secondary:     _colorHex(Colors.secondary),
            accent:        _colorHex(Colors.accent),
            error:         _colorHex(Colors.error),
            warning:       _colorHex(Colors.warning),
            success:       _colorHex(Colors.success),
            info:          _colorHex(Colors.info),
            text:          _colorHex(Colors.text),
            textSecondary: _colorHex(Colors.textSecondary),
            textDisabled:  _colorHex(Colors.textDisabled),
            isLight:       Colors._isLight
        };

        // Read ANSI palette once for all consumers
        var ansi = _readAnsiPalette();
        if (ansi)
            palette.ansiColors = ansi;

        // Write JSON
        _jsonWriter.command = [
            "sh", "-c",
            'printf "%s" "$1" > "$2"', "sh",
            JSON.stringify(palette, null, 2),
            jsonPath
        ];
        _jsonWriter.running = true;

        // Write shell vars
        var sh = "# Auto-generated by quickshell ColorExportService\n";
        var keys = Object.keys(palette);
        for (var i = 0; i < keys.length; i++) {
            var k = keys[i];
            var v = palette[k];
            if (k === "ansiColors") continue; // handled separately below
            // QUICKSHELL_COLOR_BACKGROUND="#0a0a0c" etc.
            var envName = "QUICKSHELL_COLOR_" + k.replace(/([A-Z])/g, "_$1").toUpperCase();
            sh += envName + '="' + v + '"\n';
        }
        // ANSI palette as indexed vars: QUICKSHELL_ANSI_0="#..." through QUICKSHELL_ANSI_15="#..."
        if (ansi) {
            for (var ai = 0; ai < 16; ai++) {
                if (ansi[ai])
                    sh += 'QUICKSHELL_ANSI_' + ai + '="' + ansi[ai] + '"\n';
            }
        }
        _shWriter.command = [
            "sh", "-c",
            'printf "%s" "$1" > "$2"', "sh",
            sh, shellPath
        ];
        _shWriter.running = true;

        // Fire hook
        HookService.fireHook("colors-changed", jsonPath);

        // Built-in propagation (pass ansi to avoid re-reading)
        _propagateGhostty(palette, ansi);
        _propagateKitty(palette, ansi);
        _propagateGtkScheme(palette);

        Logger.d("ColorExport", "exported palette to " + jsonPath);
    }

    // ── Built-in ghostty config fragment ────────────────
    // Writes a ghostty-compatible config file. User includes it via:
    //   config-file = ~/.local/state/quickshell/ghostty-colors
    // Ghostty auto-reloads when the included file changes.
    // Includes the full 16-color ANSI palette from pywal if available.
    function _propagateGhostty(palette, ansi) {
        if (!Config.colorExportGhostty) return;
        // Strip "#" prefix — ghostty expects bare hex
        function bare(hex) { return String(hex).replace(/^#/, ""); }
        var cfg = "# Auto-generated by quickshell ColorExportService\n"
            + "background = " + bare(palette.background) + "\n"
            + "foreground = " + bare(palette.text) + "\n"
            + "cursor-color = " + bare(palette.primary) + "\n"
            + "selection-background = " + bare(palette.primary) + "\n"
            + "selection-foreground = " + bare(palette.background) + "\n";

        if (ansi) {
            for (var i = 0; i < 16; i++) {
                if (ansi[i])
                    cfg += "palette = " + i + "=" + bare(ansi[i]) + "\n";
            }
        }

        _ghosttyWriter.command = [
            "sh", "-c",
            'printf "%s" "$1" > "$2"', "sh",
            cfg, ghosttyPath
        ];
        _ghosttyWriter.running = true;
    }

    // Read the 16 ANSI colors from pywal's colors.json
    function _readAnsiPalette() {
        try {
            var raw = _walFile.text();
            if (!raw) return null;
            var data = JSON.parse(raw);
            if (!data.colors) return null;
            var result = [];
            for (var i = 0; i < 16; i++)
                result.push(data.colors["color" + i] || null);
            return result;
        } catch (e) {
            return null;
        }
    }

    property FileView _walFile: FileView {
        path: Quickshell.env("HOME") + "/.cache/wal/colors.json"
        blockLoading: true
        printErrors: false
    }

    // ── Built-in kitty remote control ────────────────
    function _propagateKitty(palette, ansi) {
        if (!Config.colorExportKitty) return;
        var args = [
            "kitty", "@", "set-colors",
            "background=" + palette.background,
            "foreground=" + palette.text,
            "cursor=" + palette.primary,
            "selection_background=" + palette.primary,
            "selection_foreground=" + palette.background
        ];
        if (ansi) {
            for (var i = 0; i < 16; i++) {
                if (ansi[i])
                    args.push("color" + i + "=" + ansi[i]);
            }
        }
        _kittyProc.command = args;
        _kittyProc.running = true;
    }

    // ── Built-in GTK dark/light scheme ───────────────
    function _propagateGtkScheme(palette) {
        if (!Config.colorExportGtkScheme) return;
        var scheme = palette.isLight ? "prefer-light" : "prefer-dark";
        _gtkProc.command = [
            "gsettings", "set", "org.gnome.desktop.interface",
            "color-scheme", scheme
        ];
        _gtkProc.running = true;
    }

    property Process _jsonWriter: Process { running: false; command: ["true"] }
    property Process _shWriter: Process { running: false; command: ["true"] }
    property Process _ghosttyWriter: Process { running: false; command: ["true"] }
    property Process _kittyProc: Process {
        running: false; command: ["true"]
        onExited: (code) => {
            if (code !== 0) Logger.d("ColorExport", "kitty @ set-colors not available (exit " + code + ")");
        }
    }
    property Process _gtkProc: Process {
        running: false; command: ["true"]
        onExited: (code) => {
            if (code !== 0) Logger.d("ColorExport", "gsettings not available (exit " + code + ")");
        }
    }

    // Initial export: wait for colors to actually be loaded before scheduling
    property Connections _readyConn: Connections {
        target: Colors
        function onColorsReadyChanged() {
            if (Colors.colorsReady && Config.colorExportEnabled)
                root._pendingExport = true;
        }
    }

    Component.onCompleted: {
        if (Config.colorExportEnabled && Colors.colorsReady)
            _pendingExport = true;
    }
}
