pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "."

// Exports active color palette to well-known files after each color change.
// Enables downstream tools (kitty, scripts, CSS generators) to pick up the
// current shell colors. Opt-in via Config.colorExportEnabled.
//
// Exports:
//   ~/.local/state/quickshell/colors-export.json  (machine-readable)
//   ~/.local/state/quickshell/colors-export.sh    (sourceable shell vars)
//
// Also fires HookService "colors-changed" with the JSON path.
QtObject {
    id: root

    readonly property string _stateDir: Quickshell.statePath("")
    readonly property string jsonPath: _stateDir + "colors-export.json"
    readonly property string shellPath: _stateDir + "colors-export.sh"

    // Debounce: wait for color transition to finish before exporting
    property bool _pendingExport: false

    property Connections _colorConn: Connections {
        target: Colors
        function onIsTransitioningChanged() {
            if (!Colors.isTransitioning && root._pendingExport) {
                root._pendingExport = false;
                root._doExport();
            }
        }
        function onBackgroundChanged() { root._scheduleExport(); }
        function onPrimaryChanged()    { root._scheduleExport(); }
        function onTextChanged()       { root._scheduleExport(); }
    }

    function _scheduleExport() {
        if (!Config.colorExportEnabled) return;
        if (Colors.isTransitioning || Colors.skipTransition) {
            root._pendingExport = true;
            return;
        }
        _exportTimer.restart();
    }

    property Timer _exportTimer: Timer {
        interval: 200
        onTriggered: root._doExport()
    }

    function _colorHex(c) {
        return Colors.withAlpha(c, 1.0).toString();
    }

    function _doExport() {
        if (!Config.colorExportEnabled) return;

        var palette = {
            background:    _colorHex(Colors.background),
            surface:       _colorHex(Colors.surface),
            primary:       _colorHex(Colors.primary),
            secondary:     _colorHex(Colors.secondary),
            accent:        _colorHex(Colors.accent),
            error:         _colorHex(Colors.error),
            warning:       _colorHex(Colors.warning),
            success:       _colorHex(Colors.success),
            info:          _colorHex(Colors.info),
            text:          _colorHex(Colors.text),
            textSecondary: _colorHex(Colors.textSecondary),
            textDisabled:  _colorHex(Colors.textDisabled),
            isLight:       Colors._isLight
        };

        // Write JSON
        _jsonWriter.command = [
            "sh", "-c",
            'printf "%s" "$1" > "$2"', "sh",
            JSON.stringify(palette, null, 2),
            jsonPath
        ];
        _jsonWriter.running = true;

        // Write shell vars
        var sh = "# Auto-generated by quickshell ColorExportService\n";
        var keys = Object.keys(palette);
        for (var i = 0; i < keys.length; i++) {
            var k = keys[i];
            var v = palette[k];
            // QUICKSHELL_COLOR_BACKGROUND="#0a0a0c" etc.
            var envName = "QUICKSHELL_COLOR_" + k.replace(/([A-Z])/g, "_$1").toUpperCase();
            sh += envName + '="' + v + '"\n';
        }
        _shWriter.command = [
            "sh", "-c",
            'printf "%s" "$1" > "$2"', "sh",
            sh, shellPath
        ];
        _shWriter.running = true;

        // Fire hook
        HookService.fireHook("colors-changed", jsonPath);

        // Built-in propagation
        _propagateKitty(palette);
        _propagateGtkScheme(palette);

        Logger.d("ColorExport", "exported palette to " + jsonPath);
    }

    // ── Built-in kitty remote control ────────────────
    function _propagateKitty(palette) {
        if (!Config.colorExportKitty) return;
        _kittyProc.command = [
            "kitty", "@", "set-colors",
            "background=" + palette.background,
            "foreground=" + palette.text,
            "cursor=" + palette.primary,
            "selection_background=" + palette.primary,
            "selection_foreground=" + palette.background
        ];
        _kittyProc.running = true;
    }

    // ── Built-in GTK dark/light scheme ───────────────
    function _propagateGtkScheme(palette) {
        if (!Config.colorExportGtkScheme) return;
        var scheme = palette.isLight ? "prefer-light" : "prefer-dark";
        _gtkProc.command = [
            "gsettings", "set", "org.gnome.desktop.interface",
            "color-scheme", scheme
        ];
        _gtkProc.running = true;
    }

    property Process _jsonWriter: Process { running: false; command: ["true"] }
    property Process _shWriter: Process { running: false; command: ["true"] }
    property Process _kittyProc: Process {
        running: false; command: ["true"]
        onExited: (code) => {
            if (code !== 0) Logger.d("ColorExport", "kitty @ set-colors not available (exit " + code + ")");
        }
    }
    property Process _gtkProc: Process {
        running: false; command: ["true"]
        onExited: (code) => {
            if (code !== 0) Logger.d("ColorExport", "gsettings not available (exit " + code + ")");
        }
    }

    // Initial export on startup (after first color load settles)
    Component.onCompleted: {
        if (Config.colorExportEnabled)
            _pendingExport = true;
    }
}
