pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Services.UPower

QtObject {
    id: root

    // ── Public state ─────────────────────────────
    readonly property bool onBattery: _onBattery
    readonly property string powerSource: _onBattery ? "battery" : "ac"

    // Active profile values (derived from AC vs battery)
    readonly property int monitorTimeout: _onBattery ? Config.powerBatMonitorTimeout : Config.powerAcMonitorTimeout
    readonly property int lockTimeout: _onBattery ? Config.powerBatLockTimeout : Config.powerAcLockTimeout
    readonly property int suspendTimeout: _onBattery ? Config.powerBatSuspendTimeout : Config.powerAcSuspendTimeout
    readonly property string suspendAction: _onBattery ? Config.powerBatSuspendAction : Config.powerAcSuspendAction

    // ── Internal ─────────────────────────────────
    property bool _onBattery: false

    // Poll power supply status
    property Timer _pollTimer: Timer {
        interval: 10000
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: _checkProc.running = true
    }

    property Process _checkProc: Process {
        running: false
        command: ["sh", "-c",
            "for f in /sys/class/power_supply/AC*/online /sys/class/power_supply/ACAD/online; do " +
            "  [ -f \"$f\" ] && cat \"$f\" 2>/dev/null && exit; " +
            "done; " +
            "echo 1"
        ]
        stdout: StdioCollector {
            onStreamFinished: {
                var val = (this.text || "").trim();
                root._onBattery = (val === "0");
            }
        }
    }

    // ── Hypridle config generation ───────────────
    property Connections _configWatcher: Connections {
        target: Config
        function onPowerAcMonitorTimeoutChanged() { root._scheduleHypridle(); }
        function onPowerAcLockTimeoutChanged() { root._scheduleHypridle(); }
        function onPowerAcSuspendTimeoutChanged() { root._scheduleHypridle(); }
        function onPowerAcSuspendActionChanged() { root._scheduleHypridle(); }
        function onPowerBatMonitorTimeoutChanged() { root._scheduleHypridle(); }
        function onPowerBatLockTimeoutChanged() { root._scheduleHypridle(); }
        function onPowerBatSuspendTimeoutChanged() { root._scheduleHypridle(); }
        function onPowerBatSuspendActionChanged() { root._scheduleHypridle(); }
    }

    onPowerSourceChanged: _scheduleHypridle()

    property Timer _hyprIdleDebounce: Timer {
        interval: 500
        onTriggered: root._writeHypridleConfig()
    }

    function _scheduleHypridle() {
        _hyprIdleDebounce.restart();
    }

    function _writeHypridleConfig() {
        var lines = [];
        lines.push("# Auto-generated by quickshell PowerService");
        lines.push("# Power source: " + root.powerSource);
        lines.push("");

        if (root.monitorTimeout > 0) {
            lines.push("listener {");
            lines.push("    timeout = " + (root.monitorTimeout * 60));
            lines.push("    on-timeout = hyprctl dispatch dpms off");
            lines.push("    on-resume = hyprctl dispatch dpms on");
            lines.push("}");
            lines.push("");
        }

        if (root.lockTimeout > 0) {
            var lockCmd = CompositorAdapter.isHyprland ? "hyprlock" : "swaylock";
            lines.push("listener {");
            lines.push("    timeout = " + (root.lockTimeout * 60));
            lines.push("    on-timeout = pidof " + lockCmd + " || " + lockCmd);
            lines.push("}");
            lines.push("");
        }

        if (root.suspendTimeout > 0) {
            var action = root.suspendAction || "suspend";
            lines.push("listener {");
            lines.push("    timeout = " + (root.suspendTimeout * 60));
            lines.push("    on-timeout = systemctl " + action);
            lines.push("}");
            lines.push("");
        }

        _pendingHypridleContent = lines.join("\n") + "\n";
        if (_writeProc.running) return; // debounce will re-trigger
        _writeProc.command = ["sh", "-c",
            "mkdir -p ~/.config/hypr && cat > ~/.config/hypr/hypridle-quickshell.conf"
        ];
        _writeProc.running = true;
    }

    property string _pendingHypridleContent: ""

    property Process _writeProc: Process {
        running: false
        stdinEnabled: true
        onStarted: {
            _writeProc.write(root._pendingHypridleContent);
            _writeProc.stdinEnabled = false;
        }
        onExited: (exitCode, exitStatus) => {
            root._pendingHypridleContent = "";
            if (exitCode === 0) {
                // Signal hypridle to reload if running
                Quickshell.execDetached(["pkill", "-USR1", "hypridle"]);
            }
        }
    }

    // ── Battery alerts ──────────────────────────
    property bool _warningFired: false
    property bool _criticalFired: false
    property var _batteryDevice: UPower.displayDevice

    property Connections _batteryWatcher: Connections {
        target: root._batteryDevice
        enabled: root._batteryDevice != null && root._batteryDevice.isPresent
        function onPercentageChanged() { root._checkBatteryAlerts(); }
        function onStateChanged() { root._checkBatteryAlerts(); }
    }

    function _checkBatteryAlerts() {
        if (!Config.batteryAlertsEnabled) return;
        if (!_batteryDevice || !_batteryDevice.isPresent) return;

        var pct = Math.round(_batteryDevice.percentage * 100);
        var charging = _batteryDevice.state === UPower.DeviceStateCharging
                    || _batteryDevice.state === UPower.DeviceStateFullyCharged;

        // Reset alerts when charging
        if (charging) {
            _warningFired = false;
            _criticalFired = false;
            return;
        }

        if (pct <= Config.batteryCriticalThreshold && !_criticalFired) {
            _criticalFired = true;
            _warningFired = true;
            ToastService.showError("Battery Critical", "Battery at " + pct + "% \u2014 plug in immediately");
            return;
        }
        if (pct <= Config.batteryWarningThreshold && !_warningFired) {
            _warningFired = true;
            ToastService.showNotice("Battery Low", "Battery at " + pct + "% \u2014 consider plugging in");
        }
    }

    Component.onCompleted: {
        // Initial config write after a delay to let Config load
        Qt.callLater(function() {
            root._scheduleHypridle();
        });
    }
}
