# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ansible = {
    pname = "ansible";
    version = "26.1.1";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/ansible/26.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ansible-26.1.1.zip";
      sha256 = "sha256-mmimQCXxEbvzmctd5HAs70FUsBPIylrpLw2UG+I8TxM=";
    };
    publisher = "redhat";
    name = "ansible";
  };
  biome = {
    pname = "biome";
    version = "2025.11.271431";
    src = fetchurl {
      url = "https://biomejs.gallery.vsassets.io/_apis/public/gallery/publisher/biomejs/extension/biome/2025.11.271431/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "biome-2025.11.271431.zip";
      sha256 = "sha256-TLm2ppAyZoCHNg3RpEFwUr/C04bkI62AK4kNS4R/j2U=";
    };
    publisher = "biomejs";
    name = "biome";
  };
  chatgpt = {
    pname = "chatgpt";
    version = "0.5.60";
    src = fetchurl {
      url = "https://openai.gallery.vsassets.io/_apis/public/gallery/publisher/openai/extension/chatgpt/0.5.60/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "chatgpt-0.5.60.zip";
      sha256 = "sha256-EA1tQ0zySsbeuVXykte3gp9LhFZQW4ytKYPv6mbf19Y=";
    };
    publisher = "openai";
    name = "chatgpt";
  };
  claude-code = {
    pname = "claude-code";
    version = "2.1.9";
    src = fetchurl {
      url = "https://anthropic.gallery.vsassets.io/_apis/public/gallery/publisher/anthropic/extension/claude-code/2.1.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "claude-code-2.1.9.zip";
      sha256 = "sha256-1zrXLaTilKY11FVBGnP4ezRT5LAefGH1UKwqz+E/sFY=";
    };
    publisher = "anthropic";
    name = "claude-code";
  };
  copilot = {
    pname = "copilot";
    version = "1.388.0";
    src = fetchurl {
      url = "https://github.gallery.vsassets.io/_apis/public/gallery/publisher/github/extension/copilot/1.388.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.388.0.zip";
      sha256 = "sha256-7RjK8+PNI+rIuRQfCwpvswAiz991dacRO2qYhcv1vhk=";
    };
    publisher = "github";
    name = "copilot";
  };
  copilot-chat = {
    pname = "copilot-chat";
    version = "0.37.2026011603";
    src = fetchurl {
      url = "https://github.gallery.vsassets.io/_apis/public/gallery/publisher/github/extension/copilot-chat/0.37.2026011603/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-chat-0.37.2026011603.zip";
      sha256 = "sha256-HIsROMQAxQ0ulyyUGZArbZeAHu/Oiyz0cFdqogTRpM0=";
    };
    publisher = "github";
    name = "copilot-chat";
  };
  explorer = {
    pname = "explorer";
    version = "1.38.0";
    src = fetchurl {
      url = "https://vitest.gallery.vsassets.io/_apis/public/gallery/publisher/vitest/extension/explorer/1.38.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "explorer-1.38.0.zip";
      sha256 = "sha256-1UTQCy40wNgjkBmVMIo/U5H182lYMdhQBh6mncTctTA=";
    };
    publisher = "vitest";
    name = "explorer";
  };
  gemini-cli-vscode-ide-companion = {
    pname = "gemini-cli-vscode-ide-companion";
    version = "0.20.0";
    src = fetchurl {
      url = "https://Google.gallery.vsassets.io/_apis/public/gallery/publisher/Google/extension/gemini-cli-vscode-ide-companion/0.20.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gemini-cli-vscode-ide-companion-0.20.0.zip";
      sha256 = "sha256-gJ7ghOOrk4kvzReqfB6ZRhFonOdpJXcPh7voBgCwqPg=";
    };
    publisher = "Google";
    name = "gemini-cli-vscode-ide-companion";
  };
  gopls = {
    pname = "gopls";
    version = "gopls/v0.21.0";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "gopls/v0.21.0";
      fetchSubmodules = false;
      sha256 = "sha256-fPG8//DWA0mzqZkYasiBdB5hw5FDRkr/3+ZXm7fNHRg=";
    };
  };
  grafana-alloy = {
    pname = "grafana-alloy";
    version = "0.2.0";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/grafana-alloy/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "grafana-alloy-0.2.0.zip";
      sha256 = "sha256-XcoiEDCPp6GzYQDhJArZBEWxSnZrSTHofIyLFegsbh0=";
    };
    publisher = "grafana";
    name = "grafana-alloy";
  };
  grafana-vscode = {
    pname = "grafana-vscode";
    version = "0.0.19";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/grafana-vscode/0.0.19/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "grafana-vscode-0.0.19.zip";
      sha256 = "sha256-TpLOMwdaEdgzWVwUcn+fO4rgLiQammWQM8LQobt8gLw=";
    };
    publisher = "grafana";
    name = "grafana-vscode";
  };
  mypy-type-checker = {
    pname = "mypy-type-checker";
    version = "2025.3.13521012";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/mypy-type-checker/2025.3.13521012/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "mypy-type-checker-2025.3.13521012.zip";
      sha256 = "sha256-CSiQWwpY/43Yx0/ppwq9f21ksqLYhr0Nv/i4+sno2Qs=";
    };
    publisher = "ms-python";
    name = "mypy-type-checker";
  };
  pdf = {
    pname = "pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    publisher = "tomoki1207";
    name = "pdf";
  };
  playwright = {
    pname = "playwright";
    version = "1.1.17";
    src = fetchurl {
      url = "https://ms-playwright.gallery.vsassets.io/_apis/public/gallery/publisher/ms-playwright/extension/playwright/1.1.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "playwright-1.1.17.zip";
      sha256 = "sha256-qIQS9rjzTJF0T6RWMJvaxOGcQmoXpIhzVHDMFxGMb/A=";
    };
    publisher = "ms-playwright";
    name = "playwright";
  };
  prom = {
    pname = "prom";
    version = "1.3.3";
    src = fetchurl {
      url = "https://ventura.gallery.vsassets.io/_apis/public/gallery/publisher/ventura/extension/prom/1.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "prom-1.3.3.zip";
      sha256 = "sha256-h8pRrPzmu8+5ZiOLALjackr4zWuFAqi1ex7Gp2iOZKk=";
    };
    publisher = "ventura";
    name = "prom";
  };
  pwc = {
    pname = "pwc";
    version = "1.2.1";
    src = fetchurl {
      url = "https://SureshNettur.gallery.vsassets.io/_apis/public/gallery/publisher/SureshNettur/extension/pwc/1.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pwc-1.2.1.zip";
      sha256 = "sha256-e+O8mPGc50eJDvXMcLmsW7ht8jTXylbVoUf+ayaYx6E=";
    };
    publisher = "SureshNettur";
    name = "pwc";
  };
  pyrefly = {
    pname = "pyrefly";
    version = "0.48.1";
    src = fetchurl {
      url = "https://meta.gallery.vsassets.io/_apis/public/gallery/publisher/meta/extension/pyrefly/0.48.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pyrefly-0.48.1.zip";
      sha256 = "sha256-bf/lEZgYEtkxrXX4qdm6mP3oay9L6mYXyWa1K8zsKrA=";
    };
    publisher = "meta";
    name = "pyrefly";
  };
  remotehub = {
    pname = "remotehub";
    version = "0.65.2025081801";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/remotehub/0.65.2025081801/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remotehub-0.65.2025081801.zip";
      sha256 = "sha256-boKDVKLo8Na799OtoPnT6JxsAvQ/HoqL3FispnN6bOA=";
    };
    publisher = "GitHub";
    name = "remotehub";
  };
  ty = {
    pname = "ty";
    version = "2026.4.0";
    src = fetchurl {
      url = "https://astral-sh.gallery.vsassets.io/_apis/public/gallery/publisher/astral-sh/extension/ty/2026.4.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ty-2026.4.0.zip";
      sha256 = "sha256-r5vM0G1TnFIQCi31iu3HaF5mFLRi/2h7UnV3SuWMyho=";
    };
    publisher = "astral-sh";
    name = "ty";
  };
  vscode-containers = {
    pname = "vscode-containers";
    version = "2.3.0";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-containers/2.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-containers-2.3.0.zip";
      sha256 = "sha256-zrEZpd2geX2G4u6LkIk3d6C7vhwZZ4lwHGQR3Z0OWY4=";
    };
    publisher = "ms-azuretools";
    name = "vscode-containers";
  };
  vscode-gitops-tools = {
    pname = "vscode-gitops-tools";
    version = "0.27.0";
    src = fetchurl {
      url = "https://weaveworks.gallery.vsassets.io/_apis/public/gallery/publisher/weaveworks/extension/vscode-gitops-tools/0.27.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-gitops-tools-0.27.0.zip";
      sha256 = "sha256-7MCKDnHCot/CL/SqZ2WuTxbqFdF75EC5WC+OxW0dcaE=";
    };
    publisher = "weaveworks";
    name = "vscode-gitops-tools";
  };
  vscode-jsonnet = {
    pname = "vscode-jsonnet";
    version = "0.7.2";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/vscode-jsonnet/0.7.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jsonnet-0.7.2.zip";
      sha256 = "sha256-Q8VzXzTdHo9h5+eCHHF1bPomPEbRsvouJcUfmFUDGMU=";
    };
    publisher = "grafana";
    name = "vscode-jsonnet";
  };
  vscode-pgsql = {
    pname = "vscode-pgsql";
    version = "1.14.0";
    src = fetchurl {
      url = "https://ms-ossdata.gallery.vsassets.io/_apis/public/gallery/publisher/ms-ossdata/extension/vscode-pgsql/1.14.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-pgsql-1.14.0.zip";
      sha256 = "sha256-/+VXsppHJlC+suEmu6d8lpryCKwfNWVA/nEYu4nhX3I=";
    };
    publisher = "ms-ossdata";
    name = "vscode-pgsql";
  };
  vscode-python-test-adapter = {
    pname = "vscode-python-test-adapter";
    version = "0.8.2";
    src = fetchurl {
      url = "https://littlefoxteam.gallery.vsassets.io/_apis/public/gallery/publisher/littlefoxteam/extension/vscode-python-test-adapter/0.8.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-python-test-adapter-0.8.2.zip";
      sha256 = "sha256-TwBPGr8bam1NSX2KRrm92DOQWeVa0k+pXT4q/isWYOI=";
    };
    publisher = "littlefoxteam";
    name = "vscode-python-test-adapter";
  };
  vscode-thunder-client = {
    pname = "vscode-thunder-client";
    version = "2.38.6";
    src = fetchurl {
      url = "https://rangav.gallery.vsassets.io/_apis/public/gallery/publisher/rangav/extension/vscode-thunder-client/2.38.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-thunder-client-2.38.6.zip";
      sha256 = "sha256-8joP2BzTuUWS0XnpHonoClrfOw03pj2Bs+q9At7LtyI=";
    };
    publisher = "rangav";
    name = "vscode-thunder-client";
  };
}
