# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ansible = {
    pname = "ansible";
    version = "26.1.3";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/ansible/26.1.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ansible-26.1.3.zip";
      sha256 = "sha256-iBAlDqi7u/srkgBBLha/JCHZnpccz37BdZ7zVJVfJYY=";
    };
    publisher = "redhat";
    name = "ansible";
  };
  biome = {
    pname = "biome";
    version = "2025.11.271431";
    src = fetchurl {
      url = "https://biomejs.gallery.vsassets.io/_apis/public/gallery/publisher/biomejs/extension/biome/2025.11.271431/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "biome-2025.11.271431.zip";
      sha256 = "sha256-TLm2ppAyZoCHNg3RpEFwUr/C04bkI62AK4kNS4R/j2U=";
    };
    publisher = "biomejs";
    name = "biome";
  };
  chatgpt = {
    pname = "chatgpt";
    version = "0.5.78";
    src = fetchurl {
      url = "https://openai.gallery.vsassets.io/_apis/public/gallery/publisher/openai/extension/chatgpt/0.5.78/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "chatgpt-0.5.78.zip";
      sha256 = "sha256-94mYuNm6IgIB2jOuyGcqnmUb1gbqO83TlkgvCoPx3Kw=";
    };
    publisher = "openai";
    name = "chatgpt";
  };
  claude-code = {
    pname = "claude-code";
    version = "2.1.61";
    src = fetchurl {
      url = "https://anthropic.gallery.vsassets.io/_apis/public/gallery/publisher/anthropic/extension/claude-code/2.1.61/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "claude-code-2.1.61.zip";
      sha256 = "sha256-9/k1hnMpDl6dTlG67e37JuNo7mKtXAsLQpX2E0fbFuM=";
    };
    publisher = "anthropic";
    name = "claude-code";
  };
  explorer = {
    pname = "explorer";
    version = "1.44.1";
    src = fetchurl {
      url = "https://vitest.gallery.vsassets.io/_apis/public/gallery/publisher/vitest/extension/explorer/1.44.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "explorer-1.44.1.zip";
      sha256 = "sha256-Ac6v4QwWpmZ8unjW3AnbPGe+JBQTUz2+v7X2/BRckcw=";
    };
    publisher = "vitest";
    name = "explorer";
  };
  gemini-cli-vscode-ide-companion = {
    pname = "gemini-cli-vscode-ide-companion";
    version = "0.20.0";
    src = fetchurl {
      url = "https://Google.gallery.vsassets.io/_apis/public/gallery/publisher/Google/extension/gemini-cli-vscode-ide-companion/0.20.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gemini-cli-vscode-ide-companion-0.20.0.zip";
      sha256 = "sha256-gJ7ghOOrk4kvzReqfB6ZRhFonOdpJXcPh7voBgCwqPg=";
    };
    publisher = "Google";
    name = "gemini-cli-vscode-ide-companion";
  };
  gopls = {
    pname = "gopls";
    version = "gopls/v0.21.1";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "gopls/v0.21.1";
      fetchSubmodules = false;
      sha256 = "sha256-D/HBqFy5pNSOhMxx/G102HuL+l+oPljsG8rPNLZjUCs=";
    };
  };
  grafana-alloy = {
    pname = "grafana-alloy";
    version = "0.2.0";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/grafana-alloy/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "grafana-alloy-0.2.0.zip";
      sha256 = "sha256-XcoiEDCPp6GzYQDhJArZBEWxSnZrSTHofIyLFegsbh0=";
    };
    publisher = "grafana";
    name = "grafana-alloy";
  };
  grafana-vscode = {
    pname = "grafana-vscode";
    version = "0.0.19";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/grafana-vscode/0.0.19/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "grafana-vscode-0.0.19.zip";
      sha256 = "sha256-TpLOMwdaEdgzWVwUcn+fO4rgLiQammWQM8LQobt8gLw=";
    };
    publisher = "grafana";
    name = "grafana-vscode";
  };
  mypy-type-checker = {
    pname = "mypy-type-checker";
    version = "2025.3.13521012";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/mypy-type-checker/2025.3.13521012/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "mypy-type-checker-2025.3.13521012.zip";
      sha256 = "sha256-CSiQWwpY/43Yx0/ppwq9f21ksqLYhr0Nv/i4+sno2Qs=";
    };
    publisher = "ms-python";
    name = "mypy-type-checker";
  };
  pdf = {
    pname = "pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    publisher = "tomoki1207";
    name = "pdf";
  };
  playwright = {
    pname = "playwright";
    version = "1.1.17";
    src = fetchurl {
      url = "https://ms-playwright.gallery.vsassets.io/_apis/public/gallery/publisher/ms-playwright/extension/playwright/1.1.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "playwright-1.1.17.zip";
      sha256 = "sha256-qIQS9rjzTJF0T6RWMJvaxOGcQmoXpIhzVHDMFxGMb/A=";
    };
    publisher = "ms-playwright";
    name = "playwright";
  };
  prom = {
    pname = "prom";
    version = "1.3.3";
    src = fetchurl {
      url = "https://ventura.gallery.vsassets.io/_apis/public/gallery/publisher/ventura/extension/prom/1.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "prom-1.3.3.zip";
      sha256 = "sha256-h8pRrPzmu8+5ZiOLALjackr4zWuFAqi1ex7Gp2iOZKk=";
    };
    publisher = "ventura";
    name = "prom";
  };
  pwc = {
    pname = "pwc";
    version = "1.2.1";
    src = fetchurl {
      url = "https://SureshNettur.gallery.vsassets.io/_apis/public/gallery/publisher/SureshNettur/extension/pwc/1.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pwc-1.2.1.zip";
      sha256 = "sha256-e+O8mPGc50eJDvXMcLmsW7ht8jTXylbVoUf+ayaYx6E=";
    };
    publisher = "SureshNettur";
    name = "pwc";
  };
  pyrefly = {
    pname = "pyrefly";
    version = "0.54.0";
    src = fetchurl {
      url = "https://meta.gallery.vsassets.io/_apis/public/gallery/publisher/meta/extension/pyrefly/0.54.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pyrefly-0.54.0.zip";
      sha256 = "sha256-Ua2aQN/iS1nPOm6EM1Kgwxd1J8T4p9flUQkHIpW3P8E=";
    };
    publisher = "meta";
    name = "pyrefly";
  };
  remotehub = {
    pname = "remotehub";
    version = "0.65.2026012801";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/remotehub/0.65.2026012801/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remotehub-0.65.2026012801.zip";
      sha256 = "sha256-/rkEJCyI0HWAoc2EyuCV4gwZnad9KMqEI00HUweVe+4=";
    };
    publisher = "GitHub";
    name = "remotehub";
  };
  ty = {
    pname = "ty";
    version = "2026.18.0";
    src = fetchurl {
      url = "https://astral-sh.gallery.vsassets.io/_apis/public/gallery/publisher/astral-sh/extension/ty/2026.18.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ty-2026.18.0.zip";
      sha256 = "sha256-cGTtEuXOqCbUd0eJtTYz6tjesHfRFHOrowHoXCegtoU=";
    };
    publisher = "astral-sh";
    name = "ty";
  };
  vscode-containers = {
    pname = "vscode-containers";
    version = "2.4.1";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-containers/2.4.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-containers-2.4.1.zip";
      sha256 = "sha256-OwxJJVW15MivWVeSlbFQNQbrxjDgpXePrPf+r3qb+As=";
    };
    publisher = "ms-azuretools";
    name = "vscode-containers";
  };
  vscode-gitops-tools = {
    pname = "vscode-gitops-tools";
    version = "0.27.0";
    src = fetchurl {
      url = "https://weaveworks.gallery.vsassets.io/_apis/public/gallery/publisher/weaveworks/extension/vscode-gitops-tools/0.27.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-gitops-tools-0.27.0.zip";
      sha256 = "sha256-7MCKDnHCot/CL/SqZ2WuTxbqFdF75EC5WC+OxW0dcaE=";
    };
    publisher = "weaveworks";
    name = "vscode-gitops-tools";
  };
  vscode-jsonnet = {
    pname = "vscode-jsonnet";
    version = "0.7.4";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/vscode-jsonnet/0.7.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jsonnet-0.7.4.zip";
      sha256 = "sha256-oz+oRjea2/ZDZPHvOXRdmHMCingAWWzs3u1e1r0iUTw=";
    };
    publisher = "grafana";
    name = "vscode-jsonnet";
  };
  vscode-pgsql = {
    pname = "vscode-pgsql";
    version = "1.16.0";
    src = fetchurl {
      url = "https://ms-ossdata.gallery.vsassets.io/_apis/public/gallery/publisher/ms-ossdata/extension/vscode-pgsql/1.16.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-pgsql-1.16.0.zip";
      sha256 = "sha256-ILVSR2zid/uUyK0S2O39ztyC8rsW74nvhhpmIv/cEpM=";
    };
    publisher = "ms-ossdata";
    name = "vscode-pgsql";
  };
  vscode-python-test-adapter = {
    pname = "vscode-python-test-adapter";
    version = "0.8.2";
    src = fetchurl {
      url = "https://littlefoxteam.gallery.vsassets.io/_apis/public/gallery/publisher/littlefoxteam/extension/vscode-python-test-adapter/0.8.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-python-test-adapter-0.8.2.zip";
      sha256 = "sha256-TwBPGr8bam1NSX2KRrm92DOQWeVa0k+pXT4q/isWYOI=";
    };
    publisher = "littlefoxteam";
    name = "vscode-python-test-adapter";
  };
  vscode-thunder-client = {
    pname = "vscode-thunder-client";
    version = "2.39.9";
    src = fetchurl {
      url = "https://rangav.gallery.vsassets.io/_apis/public/gallery/publisher/rangav/extension/vscode-thunder-client/2.39.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-thunder-client-2.39.9.zip";
      sha256 = "sha256-pHshB0DbJwfwEAp7+RyfDkpvANyOcAlLyuXKdM+NNN4=";
    };
    publisher = "rangav";
    name = "vscode-thunder-client";
  };
}
