# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpine-js-intellisense = {
    pname = "alpine-js-intellisense";
    version = "1.2.0";
    src = fetchurl {
      url = "https://adrianwilczynski.gallery.vsassets.io/_apis/public/gallery/publisher/adrianwilczynski/extension/alpine-js-intellisense/1.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "alpine-js-intellisense-1.2.0.zip";
      sha256 = "sha256-Klx5ZvV06lXIJ3Q/mzq3KBjPpdROoxDkgEu7MBO+RhI=";
    };
    publisher = "adrianwilczynski";
    name = "alpine-js-intellisense";
  };
  ansible = {
    pname = "ansible";
    version = "25.8.1";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/ansible/25.8.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ansible-25.8.1.zip";
      sha256 = "sha256-TXXOuayVohQPp+yQAHbsZDr/UYtyHmUkaLU+lADpjDU=";
    };
    publisher = "redhat";
    name = "ansible";
  };
  biome = {
    pname = "biome";
    version = "2025.7.41733";
    src = fetchurl {
      url = "https://biomejs.gallery.vsassets.io/_apis/public/gallery/publisher/biomejs/extension/biome/2025.7.41733/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "biome-2025.7.41733.zip";
      sha256 = "sha256-wWyLIjNOBjIe72ed+wwfQWGH7Vzuea/0Xux0XJkhAkY=";
    };
    publisher = "biomejs";
    name = "biome";
  };
  chatgpt = {
    pname = "chatgpt";
    version = "0.5.5";
    src = fetchurl {
      url = "https://openai.gallery.vsassets.io/_apis/public/gallery/publisher/openai/extension/chatgpt/0.5.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "chatgpt-0.5.5.zip";
      sha256 = "sha256-drpduDyHT/Aem/55Cjnu01aNe/ijlNgLSpKvtg9WU40=";
    };
    publisher = "openai";
    name = "chatgpt";
  };
  claude-code = {
    pname = "claude-code";
    version = "1.0.109";
    src = fetchurl {
      url = "https://anthropic.gallery.vsassets.io/_apis/public/gallery/publisher/anthropic/extension/claude-code/1.0.109/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "claude-code-1.0.109.zip";
      sha256 = "sha256-g79/+Jzh8HBhndFMQ+qmP2iNMqJw75c5BrLPsiJg0gc=";
    };
    publisher = "anthropic";
    name = "claude-code";
  };
  context7-mcp = {
    pname = "context7-mcp";
    version = "1.0.1";
    src = fetchurl {
      url = "https://upstash.gallery.vsassets.io/_apis/public/gallery/publisher/upstash/extension/context7-mcp/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "context7-mcp-1.0.1.zip";
      sha256 = "sha256-q6SkIy7eZ9H1yOnZygkcXQcpTK4eu6/jjud1wqEL2Mw=";
    };
    publisher = "upstash";
    name = "context7-mcp";
  };
  copilot = {
    pname = "copilot";
    version = "1.367.1777";
    src = fetchurl {
      url = "https://github.gallery.vsassets.io/_apis/public/gallery/publisher/github/extension/copilot/1.367.1777/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.367.1777.zip";
      sha256 = "sha256-6cfVLuzoMy6bVd8u8nZh7QU6lKvO20/G9IHmRe6yNVs=";
    };
    publisher = "github";
    name = "copilot";
  };
  copilot-chat = {
    pname = "copilot-chat";
    version = "0.31.2025090803";
    src = fetchurl {
      url = "https://github.gallery.vsassets.io/_apis/public/gallery/publisher/github/extension/copilot-chat/0.31.2025090803/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-chat-0.31.2025090803.zip";
      sha256 = "sha256-pgBNrRF8SRWUKyUFuiMyQXn6ap0Ds0eeVOrfVQn5RRs=";
    };
    publisher = "github";
    name = "copilot-chat";
  };
  explorer = {
    pname = "explorer";
    version = "1.28.2";
    src = fetchurl {
      url = "https://vitest.gallery.vsassets.io/_apis/public/gallery/publisher/vitest/extension/explorer/1.28.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "explorer-1.28.2.zip";
      sha256 = "sha256-r1KCT6UYgoCPRRxy+dmJLkwUW2yRixBwfYra4kSJYB0=";
    };
    publisher = "vitest";
    name = "explorer";
  };
  gemini-cli-vscode-ide-companion = {
    pname = "gemini-cli-vscode-ide-companion";
    version = "0.2.2";
    src = fetchurl {
      url = "https://Google.gallery.vsassets.io/_apis/public/gallery/publisher/Google/extension/gemini-cli-vscode-ide-companion/0.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gemini-cli-vscode-ide-companion-0.2.2.zip";
      sha256 = "sha256-zQ8616UT9pR8+PYP903m5/VVfbIHpZ0DEVq+XO0e4i0=";
    };
    publisher = "Google";
    name = "gemini-cli-vscode-ide-companion";
  };
  gopls = {
    pname = "gopls";
    version = "gopls/v0.20.0";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "gopls/v0.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-DYYitsrdH4nujDFJgdkObEpgElhXI7Yk2IpA/EVVLVo=";
    };
  };
  grafana-alloy = {
    pname = "grafana-alloy";
    version = "0.2.0";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/grafana-alloy/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "grafana-alloy-0.2.0.zip";
      sha256 = "sha256-XcoiEDCPp6GzYQDhJArZBEWxSnZrSTHofIyLFegsbh0=";
    };
    publisher = "grafana";
    name = "grafana-alloy";
  };
  grafana-vscode = {
    pname = "grafana-vscode";
    version = "0.0.19";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/grafana-vscode/0.0.19/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "grafana-vscode-0.0.19.zip";
      sha256 = "sha256-TpLOMwdaEdgzWVwUcn+fO4rgLiQammWQM8LQobt8gLw=";
    };
    publisher = "grafana";
    name = "grafana-vscode";
  };
  htmx-attributes = {
    pname = "htmx-attributes";
    version = "0.8.0";
    src = fetchurl {
      url = "https://craigrbroughton.gallery.vsassets.io/_apis/public/gallery/publisher/craigrbroughton/extension/htmx-attributes/0.8.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "htmx-attributes-0.8.0.zip";
      sha256 = "sha256-TsemPZkq2Z13/vahRaP7z206BJaCZ1TR6OVv6aeDvyk=";
    };
    publisher = "craigrbroughton";
    name = "htmx-attributes";
  };
  hyprland = {
    pname = "hyprland";
    version = "0.1.2";
    src = fetchurl {
      url = "https://ewen-lbh.gallery.vsassets.io/_apis/public/gallery/publisher/ewen-lbh/extension/hyprland/0.1.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "hyprland-0.1.2.zip";
      sha256 = "sha256-GaDpbkqNyIElSBnHwxc2ntmEVAGwL9XlNIBWNo7pvwM=";
    };
    publisher = "ewen-lbh";
    name = "hyprland";
  };
  mypy-type-checker = {
    pname = "mypy-type-checker";
    version = "2025.3.12271015";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/mypy-type-checker/2025.3.12271015/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "mypy-type-checker-2025.3.12271015.zip";
      sha256 = "sha256-IeWhMA1ht2npPVDqJmv3IOmrlKp9uuhycGNT7h+rNks=";
    };
    publisher = "ms-python";
    name = "mypy-type-checker";
  };
  pdf = {
    pname = "pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    publisher = "tomoki1207";
    name = "pdf";
  };
  playwright = {
    pname = "playwright";
    version = "1.1.15";
    src = fetchurl {
      url = "https://ms-playwright.gallery.vsassets.io/_apis/public/gallery/publisher/ms-playwright/extension/playwright/1.1.15/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "playwright-1.1.15.zip";
      sha256 = "sha256-1fdUyzJitFfl/cVMOjEiuBS/+FTGttilXoZ8txZMmVs=";
    };
    publisher = "ms-playwright";
    name = "playwright";
  };
  prom = {
    pname = "prom";
    version = "1.3.3";
    src = fetchurl {
      url = "https://ventura.gallery.vsassets.io/_apis/public/gallery/publisher/ventura/extension/prom/1.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "prom-1.3.3.zip";
      sha256 = "sha256-h8pRrPzmu8+5ZiOLALjackr4zWuFAqi1ex7Gp2iOZKk=";
    };
    publisher = "ventura";
    name = "prom";
  };
  pwc = {
    pname = "pwc";
    version = "1.0.1";
    src = fetchurl {
      url = "https://SureshNettur.gallery.vsassets.io/_apis/public/gallery/publisher/SureshNettur/extension/pwc/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pwc-1.0.1.zip";
      sha256 = "sha256-e9Z6PZQ8yWs83jpBuVdBLlePOYO0qUvBcbYkOOc4vVI=";
    };
    publisher = "SureshNettur";
    name = "pwc";
  };
  remotehub = {
    pname = "remotehub";
    version = "0.65.2025081801";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/remotehub/0.65.2025081801/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remotehub-0.65.2025081801.zip";
      sha256 = "sha256-boKDVKLo8Na799OtoPnT6JxsAvQ/HoqL3FispnN6bOA=";
    };
    publisher = "GitHub";
    name = "remotehub";
  };
  snyk-vulnerability-scanner = {
    pname = "snyk-vulnerability-scanner";
    version = "2.24.0";
    src = fetchurl {
      url = "https://snyk-security.gallery.vsassets.io/_apis/public/gallery/publisher/snyk-security/extension/snyk-vulnerability-scanner/2.24.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "snyk-vulnerability-scanner-2.24.0.zip";
      sha256 = "sha256-enhX0h14zmZLmXDSTAwHO1OO7hiQ9rRVlXFsKKpOTUU=";
    };
    publisher = "snyk-security";
    name = "snyk-vulnerability-scanner";
  };
  specstory-vscode = {
    pname = "specstory-vscode";
    version = "0.19.1";
    src = fetchurl {
      url = "https://specstory.gallery.vsassets.io/_apis/public/gallery/publisher/specstory/extension/specstory-vscode/0.19.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "specstory-vscode-0.19.1.zip";
      sha256 = "sha256-ivCZL7lJ1G3sb2VQyoxO4KdG7dHJldagpYlmYpOdmVo=";
    };
    publisher = "specstory";
    name = "specstory-vscode";
  };
  tailwind-color-matcher = {
    pname = "tailwind-color-matcher";
    version = "1.0.8";
    src = fetchurl {
      url = "https://OmriGrossman.gallery.vsassets.io/_apis/public/gallery/publisher/OmriGrossman/extension/tailwind-color-matcher/1.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tailwind-color-matcher-1.0.8.zip";
      sha256 = "sha256-WfFg1h5tY43W9YqgXkHDlxjRquFupuvLBwotTw0XoNk=";
    };
    publisher = "OmriGrossman";
    name = "tailwind-color-matcher";
  };
  tailwind-fold = {
    pname = "tailwind-fold";
    version = "0.2.0";
    src = fetchurl {
      url = "https://stivo.gallery.vsassets.io/_apis/public/gallery/publisher/stivo/extension/tailwind-fold/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tailwind-fold-0.2.0.zip";
      sha256 = "sha256-yH3eA5jgBwxqnpFQkg91KQMkQps5iM1v783KQkQcWUU=";
    };
    publisher = "stivo";
    name = "tailwind-fold";
  };
  templ = {
    pname = "templ";
    version = "0.0.35";
    src = fetchurl {
      url = "https://a-h.gallery.vsassets.io/_apis/public/gallery/publisher/a-h/extension/templ/0.0.35/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "templ-0.0.35.zip";
      sha256 = "sha256-WIBJorljcnoPUrQCo1eyFb6vQ5lcxV0i+QJlJdzZYE0=";
    };
    publisher = "a-h";
    name = "templ";
  };
  ty = {
    pname = "ty";
    version = "2025.41.12461352";
    src = fetchurl {
      url = "https://astral-sh.gallery.vsassets.io/_apis/public/gallery/publisher/astral-sh/extension/ty/2025.41.12461352/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ty-2025.41.12461352.zip";
      sha256 = "sha256-pd0pOg6AVRwHe/OoJOBYAU3NL9RstXsvGzMR3sktzII=";
    };
    publisher = "astral-sh";
    name = "ty";
  };
  vscode-containers = {
    pname = "vscode-containers";
    version = "2.1.0";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-containers/2.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-containers-2.1.0.zip";
      sha256 = "sha256-96JLAM2b/FUR1TA/u9GPdQJmhSGUNMarbuhEhID8c6g=";
    };
    publisher = "ms-azuretools";
    name = "vscode-containers";
  };
  vscode-gitops-tools = {
    pname = "vscode-gitops-tools";
    version = "0.27.0";
    src = fetchurl {
      url = "https://weaveworks.gallery.vsassets.io/_apis/public/gallery/publisher/weaveworks/extension/vscode-gitops-tools/0.27.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-gitops-tools-0.27.0.zip";
      sha256 = "sha256-7MCKDnHCot/CL/SqZ2WuTxbqFdF75EC5WC+OxW0dcaE=";
    };
    publisher = "weaveworks";
    name = "vscode-gitops-tools";
  };
  vscode-jsonnet = {
    pname = "vscode-jsonnet";
    version = "0.7.2";
    src = fetchurl {
      url = "https://grafana.gallery.vsassets.io/_apis/public/gallery/publisher/grafana/extension/vscode-jsonnet/0.7.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jsonnet-0.7.2.zip";
      sha256 = "sha256-Q8VzXzTdHo9h5+eCHHF1bPomPEbRsvouJcUfmFUDGMU=";
    };
    publisher = "grafana";
    name = "vscode-jsonnet";
  };
  vscode-pgsql = {
    pname = "vscode-pgsql";
    version = "1.8.0";
    src = fetchurl {
      url = "https://ms-ossdata.gallery.vsassets.io/_apis/public/gallery/publisher/ms-ossdata/extension/vscode-pgsql/1.8.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-pgsql-1.8.0.zip";
      sha256 = "sha256-/d4/AsQMm9XGEytgsZA94qbR19kWTAysm0GFG2tcm9s=";
    };
    publisher = "ms-ossdata";
    name = "vscode-pgsql";
  };
  vscode-thunder-client = {
    pname = "vscode-thunder-client";
    version = "2.37.7";
    src = fetchurl {
      url = "https://rangav.gallery.vsassets.io/_apis/public/gallery/publisher/rangav/extension/vscode-thunder-client/2.37.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-thunder-client-2.37.7.zip";
      sha256 = "sha256-6uTT2WlWylc7xkvVIZTvFCMZEluKUM3epLZm4I0FaT4=";
    };
    publisher = "rangav";
    name = "vscode-thunder-client";
  };
}
