[alpine-js-intellisense]
src.vsmarketplace = "adrianwilczynski.alpine-js-intellisense"
fetch.vsmarketplace = "adrianwilczynski.alpine-js-intellisense"
passthru = { publisher = "adrianwilczynski", name = "alpine-js-intellisense" }

[ansible]
src.vsmarketplace = "redhat.ansible"
fetch.vsmarketplace = "redhat.ansible"
passthru = { publisher = "redhat", name = "ansible" }

[biome]
src.vsmarketplace = "biomejs.biome"
fetch.vsmarketplace = "biomejs.biome"
passthru = { publisher = "biomejs", name = "biome" }

[claude-code-chat]
src.vsmarketplace = "AndrePimenta.claude-code-chat"
fetch.vsmarketplace = "AndrePimenta.claude-code-chat"
passthru = { publisher = "AndrePimenta", name = "claude-code-chat" }

[pwc]
src.vsmarketplace = "SureshNettur.pwc"
fetch.vsmarketplace = "SureshNettur.pwc"
passthru = { publisher = "SureshNettur", name = "pwc" }

[claude-dev]
src.vsmarketplace = "saoudrizwan.claude-dev"
fetch.vsmarketplace = "saoudrizwan.claude-dev"
passthru = { publisher = "saoudrizwan", name = "claude-dev" }

[copilot]
src.vsmarketplace = "github.copilot"
fetch.vsmarketplace = "github.copilot"
passthru = { publisher = "github", name = "copilot" }

[explorer]
src.vsmarketplace = "vitest.explorer"
fetch.vsmarketplace = "vitest.explorer"
passthru = { publisher = "vitest", name = "explorer" }

[gopls]
src.github_tag = "golang/tools"
src.include_regex = "gopls/v[0-9]+\\.[0-9]+\\.[0-9]+"
fetch.github = "golang/tools"

[grafana-alloy]
src.vsmarketplace = "grafana.grafana-alloy"
fetch.vsmarketplace = "grafana.grafana-alloy"
passthru = { publisher = "grafana", name = "grafana-alloy" }

[grafana-vscode]
src.vsmarketplace = "grafana.grafana-vscode"
fetch.vsmarketplace = "grafana.grafana-vscode"
passthru = { publisher = "grafana", name = "grafana-vscode" }

[htmx-attributes]
src.vsmarketplace = "craigrbroughton.htmx-attributes"
fetch.vsmarketplace = "craigrbroughton.htmx-attributes"
passthru = { publisher = "craigrbroughton", name = "htmx-attributes" }

[mypy-type-checker]
src.vsmarketplace = "ms-python.mypy-type-checker"
fetch.vsmarketplace = "ms-python.mypy-type-checker"
passthru = { publisher = "ms-python", name = "mypy-type-checker" }

[pdf]
src.vsmarketplace = "tomoki1207.pdf"
fetch.vsmarketplace = "tomoki1207.pdf"
passthru = { publisher = "tomoki1207", name = "pdf" }

[playwright]
src.vsmarketplace = "ms-playwright.playwright"
fetch.vsmarketplace = "ms-playwright.playwright"
passthru = { publisher = "ms-playwright", name = "playwright" }

[prom]
src.vsmarketplace = "ventura.prom"
fetch.vsmarketplace = "ventura.prom"
passthru = { publisher = "ventura", name = "prom" }

[remotehub]
src.vsmarketplace = "GitHub.remotehub"
fetch.vsmarketplace = "GitHub.remotehub"
passthru = { publisher = "GitHub", name = "remotehub" }

[specstory-vscode]
src.vsmarketplace = "specstory.specstory-vscode"
fetch.vsmarketplace = "specstory.specstory-vscode"
passthru = { publisher = "specstory", name = "specstory-vscode" }

[sqlite-viewer]
src.vsmarketplace = "qwtel.sqlite-viewer"
fetch.vsmarketplace = "qwtel.sqlite-viewer"
passthru = { publisher = "qwtel", name = "sqlite-viewer" }

[snyk-vulnerability-scanner]
src.vsmarketplace = "snyk-security.snyk-vulnerability-scanner"
fetch.vsmarketplace = "snyk-security.snyk-vulnerability-scanner"
passthru = { publisher = "snyk-security", name = "snyk-vulnerability-scanner" }

[tailwind-color-matcher]
src.vsmarketplace = "OmriGrossman.tailwind-color-matcher"
fetch.vsmarketplace = "OmriGrossman.tailwind-color-matcher"
passthru = { publisher = "OmriGrossman", name = "tailwind-color-matcher" }

[tailwind-fold]
src.vsmarketplace = "stivo.tailwind-fold"
fetch.vsmarketplace = "stivo.tailwind-fold"
passthru = { publisher = "stivo", name = "tailwind-fold" }

[templ]
src.vsmarketplace = "a-h.templ"
fetch.vsmarketplace = "a-h.templ"
passthru = { publisher = "a-h", name = "templ" }

[ty]
src.vsmarketplace = "astral-sh.ty"
fetch.vsmarketplace = "astral-sh.ty"
passthru = { publisher = "astral-sh", name = "ty" }

[vscode-containers]
src.vsmarketplace = "ms-azuretools.vscode-containers"
fetch.vsmarketplace = "ms-azuretools.vscode-containers"
passthru = { publisher = "ms-azuretools", name = "vscode-containers" }

[vscode-gitops-tools]
src.vsmarketplace = "weaveworks.vscode-gitops-tools"
fetch.vsmarketplace = "weaveworks.vscode-gitops-tools"
passthru = { publisher = "weaveworks", name = "vscode-gitops-tools" }

[vscode-jsonnet]
src.vsmarketplace = "grafana.vscode-jsonnet"
fetch.vsmarketplace = "grafana.vscode-jsonnet"
passthru = { publisher = "grafana", name = "vscode-jsonnet" }

[vscode-pgsql]
src.vsmarketplace = "ms-ossdata.vscode-pgsql"
fetch.vsmarketplace = "ms-ossdata.vscode-pgsql"
passthru = { publisher = "ms-ossdata", name = "vscode-pgsql" }

[vscode-thunder-client]
src.vsmarketplace = "rangav.vscode-thunder-client"
fetch.vsmarketplace = "rangav.vscode-thunder-client"
passthru = { publisher = "rangav", name = "vscode-thunder-client" }
