#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
instance_id=""
output_dir="/tmp/surface-matrix"
delay_seconds="1.6"
crop_mode="monitor"
workspace_target="auto"
surfaces=(
  "networkMenu"
  "vpnMenu"
  "audioMenu"
  "weatherMenu"
  "dateTimeMenu"
  "notifCenter"
  "controlCenter"
  "systemMonitor"
)

usage() {
  cat <<'EOF'
Usage: capture-surface-matrix.sh [--output-dir DIR] [--delay SECONDS] [--crop surface|monitor|usable] [--workspace current|auto|NAME]

Capture the high-risk popup/panel surfaces on the currently focused monitor.
This produces review artifacts for manual inspection, not PASS/WARN/FAIL results.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id)
      instance_id="${2:-}"
      shift 2
      ;;
    --output-dir)
      output_dir="${2:-}"
      shift 2
      ;;
    --delay)
      delay_seconds="${2:-}"
      shift 2
      ;;
    --crop)
      crop_mode="${2:-}"
      shift 2
      ;;
    --workspace)
      workspace_target="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "${output_dir}"
surface_args=()
if [[ -n "${instance_id}" ]]; then
  surface_args+=(--id "${instance_id}")
fi

source "${script_dir}/gallery-lib.sh"

write_gallery() {
  local output_dir="$1"
  local title="Surface Matrix"
  local script_name="capture-surface-matrix.sh"
  local gallery_path="${output_dir}/index.html"
  local baseline_dir="${output_dir}/baselines"

  {
    cat <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
EOF
    render_gallery_css
    cat <<EOF
</head>
<body>

<div id="lightbox" onclick="if(event.target === this) closeLightbox()">
  <span class="lightbox-close" onclick="closeLightbox()">&times;</span>
  <div class="lightbox-nav">
    <button onclick="navigateLightbox(-1)">&lsaquo;</button>
    <button onclick="navigateLightbox(1)">&rsaquo;</button>
  </div>
  <img src="" alt="Lightbox">
</div>

<header>
  <div class="title-area">
    <h1>${title}</h1>
    <p>Generated by <code>${script_name}</code></p>
  </div>
  
  <div class="progress-container">
    <span class="progress-text">0 / 0 reviewed (0%)</span>
    <div class="progress-bar"><div class="progress-fill"></div></div>
    <button class="btn" onclick="exportReport()">Export PR Report</button>
  </div>

  <div class="controls">
    <button id="diffFilter" class="btn" onclick="toggleDiffFilter(this)">Filter by Diff</button>
    <input type="text" id="filterInput" placeholder="Filter by filename..." oninput="filterCards()">
  </div>
</header>

<main>
  <div class="grid">
EOF

    while IFS= read -r image_path; do
      rel_image_path="${image_path#${output_dir}/}"
      image_name="$(basename "${image_path}")"
      local baseline_path=""
      [[ -f "${baseline_dir}/${image_name}" ]] && baseline_path="baselines/${image_name}"
      
      # networkMenu-monitor.png -> networkMenu
      local surface="${image_name%-*}"
      local repro="./scripts/capture-surface-matrix.sh"

      render_card "${rel_image_path}" "${image_name}" "${baseline_path}" "${repro}"
    done < <(find "${output_dir}" -maxdepth 1 -type f -name '*.png' | sort)

    cat <<EOF
  </div>
</main>
EOF
    render_gallery_js
    printf '</body></html>\n'
  } > "${gallery_path}"
}

for surface in "${surfaces[@]}"; do
  bash "${script_dir}/capture-surface-viewport.sh" \
    "${surface_args[@]}" \
    --surface "${surface}" \
    --delay "${delay_seconds}" \
    --crop "${crop_mode}" \
    --workspace "${workspace_target}" \
    --output "${output_dir}/${surface}-${crop_mode}.png"
done

write_gallery "${output_dir}"

printf '[INFO] Saved surface review artifacts for the %s matrix to %s\n' "${crop_mode}" "${output_dir}"
printf '[INFO] Saved review gallery to %s/index.html\n' "${output_dir}"
