#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
runtime_root="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/quickshell/by-id"
instance_id=""
settings_preset="portrait"
surface_crop="monitor"
workspace_target="auto"
output_dir="/tmp/panel-qa-matrix"
settings_delay="2.5"
surface_delay="1.6"
settings_deep_scroll_y=""
run_settings=1
run_surfaces=1

write_gallery() {
  local gallery_path="$1"
  local rel_dir
  local image_path
  local image_name
  local rel_image_path

  {
    cat <<'EOF'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Panel QA Matrix</title>
  <style>
    :root {
      color-scheme: dark;
      --bg: #111318;
      --panel: #1a1f29;
      --border: #2b3342;
      --text: #e6ebf2;
      --muted: #9aa6b2;
      --accent: #7aa2ff;
    }
    body {
      margin: 0;
      padding: 24px;
      background: var(--bg);
      color: var(--text);
      font: 14px/1.5 system-ui, sans-serif;
    }
    h1, h2 {
      margin: 0 0 12px;
    }
    p {
      margin: 0 0 16px;
      color: var(--muted);
    }
    .section {
      margin-top: 28px;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 16px;
    }
    .card {
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 14px;
      overflow: hidden;
    }
    .card a {
      color: inherit;
      text-decoration: none;
      display: block;
    }
    .card img {
      display: block;
      width: 100%;
      height: auto;
      background: #0b0d12;
    }
    .meta {
      padding: 10px 12px 12px;
    }
    .name {
      font-weight: 600;
      margin-bottom: 4px;
    }
    .path {
      color: var(--muted);
      font-size: 12px;
      word-break: break-all;
    }
  </style>
</head>
<body>
  <h1>Panel QA Matrix</h1>
  <p>Generated by <code>capture-panel-matrix.sh</code>. Click any image to open the full file.</p>
EOF

    while IFS= read -r rel_dir; do
      printf '  <div class="section">\n'
      printf '    <h2>%s</h2>\n' "${rel_dir}"
      printf '    <div class="grid">\n'

      while IFS= read -r image_path; do
        rel_image_path="${image_path#${output_dir}/}"
        image_name="$(basename "${image_path}")"
        printf '      <div class="card">\n'
        printf '        <a href="%s">\n' "${rel_image_path}"
        printf '          <img src="%s" alt="%s">\n' "${rel_image_path}" "${image_name}"
        printf '          <div class="meta">\n'
        printf '            <div class="name">%s</div>\n' "${image_name}"
        printf '            <div class="path">%s</div>\n' "${rel_image_path}"
        printf '          </div>\n'
        printf '        </a>\n'
        printf '      </div>\n'
      done < <(find "${output_dir}/${rel_dir}" -maxdepth 1 -type f -name '*.png' | sort)

      printf '    </div>\n'
      printf '  </div>\n'
    done < <(find "${output_dir}" -mindepth 1 -maxdepth 1 -type d \( -name 'settings-*' -o -name 'surfaces-*' \) -printf '%f\n' | sort)

    printf '</body>\n</html>\n'
  } > "${gallery_path}"
}

usage() {
  cat <<'EOF'
Usage: capture-panel-matrix.sh [--output-dir DIR] [--settings-preset portrait|laptop|wide] [--surface-crop monitor|usable] [--workspace current|auto|NAME] [--settings-delay SECONDS] [--surface-delay SECONDS] [--settings-deep-scroll-y PX] [--skip-settings] [--skip-surfaces]

Capture the shared panel QA artifact set:
  - high-risk settings tab screenshots
  - high-risk popup/panel surface screenshots
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id)
      instance_id="${2:-}"
      shift 2
      ;;
    --output-dir)
      output_dir="${2:-}"
      shift 2
      ;;
    --settings-preset)
      settings_preset="${2:-}"
      shift 2
      ;;
    --surface-crop)
      surface_crop="${2:-}"
      shift 2
      ;;
    --workspace)
      workspace_target="${2:-}"
      shift 2
      ;;
    --settings-delay)
      settings_delay="${2:-}"
      shift 2
      ;;
    --surface-delay)
      surface_delay="${2:-}"
      shift 2
      ;;
    --settings-deep-scroll-y)
      settings_deep_scroll_y="${2:-}"
      shift 2
      ;;
    --skip-settings)
      run_settings=0
      shift
      ;;
    --skip-surfaces)
      run_surfaces=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -n "${settings_deep_scroll_y}" ]] && ! [[ "${settings_deep_scroll_y}" =~ ^[0-9]+$ ]]; then
  printf 'settings-deep-scroll-y must be a non-negative integer.\n' >&2
  exit 2
fi

discover_instances_from_pid() {
  local pid
  local resolved
  local ids=()

  while IFS= read -r pid; do
    [[ -n "${pid}" ]] || continue
    resolved="$(readlink -f "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/quickshell/by-pid/${pid}" 2>/dev/null || true)"
    if [[ -n "${resolved}" && -S "${resolved}/ipc.sock" ]]; then
      ids+=("$(basename "${resolved}")")
    fi
  done < <(ps -eo pid=,comm=,args= | awk '$2 ~ /quickshell/ || $3 ~ /quickshell/ { print $1 }')

  printf '%s\n' "${ids[@]}" | awk 'NF && !seen[$0]++'
}

discover_instance() {
  local ids=()
  local dir

  mapfile -t ids < <(discover_instances_from_pid)
  if (( ${#ids[@]} == 1 )); then
    printf '%s\n' "${ids[0]}"
    return 0
  fi

  if (( ${#ids[@]} == 0 )) && [[ -d "${runtime_root}" ]]; then
    while IFS= read -r dir; do
      ids+=("$(basename "${dir}")")
    done < <(find "${runtime_root}" -mindepth 1 -maxdepth 1 -type d -exec test -S '{}/ipc.sock' ';' -print 2>/dev/null | sort)
  fi

  if (( ${#ids[@]} == 1 )); then
    printf '%s\n' "${ids[0]}"
    return 0
  fi

  return 1
}

main() {
  if (( run_settings == 0 && run_surfaces == 0 )); then
    printf 'Nothing to capture. Remove at least one --skip-* flag.\n' >&2
    exit 2
  fi

  if (( run_surfaces == 1 )) && [[ -z "${instance_id}" ]]; then
    instance_id="$(discover_instance || true)"
    if [[ -z "${instance_id}" ]]; then
      printf 'Could not uniquely resolve a live QuickShell instance for surface capture. Re-run with --id INSTANCE_ID.\n' >&2
      exit 1
    fi
  fi

  mkdir -p "${output_dir}"

  if (( run_settings == 1 )); then
    local deep_scroll_y="${settings_deep_scroll_y}"
    if [[ -z "${deep_scroll_y}" && "${settings_preset}" == "portrait" ]]; then
      deep_scroll_y="520"
    fi

    printf '[INFO] Capturing settings matrix (%s)...\n' "${settings_preset}"
    "${script_dir}/capture-settings-matrix.sh" \
      --preset "${settings_preset}" \
      --delay "${settings_delay}" \
      --workspace "${workspace_target}" \
      --output-dir "${output_dir}/settings-${settings_preset}"

    if [[ -n "${deep_scroll_y}" ]]; then
      printf '[INFO] Capturing settings matrix (%s, scroll %s)...\n' "${settings_preset}" "${deep_scroll_y}"
      "${script_dir}/capture-settings-matrix.sh" \
        --preset "${settings_preset}" \
        --delay "${settings_delay}" \
        --scroll-y "${deep_scroll_y}" \
        --workspace "${workspace_target}" \
        --output-dir "${output_dir}/settings-${settings_preset}-deep"
    fi
  fi

  if (( run_surfaces == 1 )); then
    printf '[INFO] Capturing surface matrix (%s)...\n' "${surface_crop}"
    "${script_dir}/capture-surface-matrix.sh" \
      --id "${instance_id}" \
      --crop "${surface_crop}" \
      --delay "${surface_delay}" \
      --workspace "${workspace_target}" \
      --output-dir "${output_dir}/surfaces-${surface_crop}"
  fi

  write_gallery "${output_dir}/index.html"

  printf '[INFO] Panel QA capture set written to %s\n' "${output_dir}"
  printf '[INFO] Review gallery: %s/index.html\n' "${output_dir}"
}

main "$@"
