#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

instance_id=""
output_dir="/tmp/launcher-matrix"
delay_seconds="1.2"
crop_mode="usable"
workspace_target="auto"
query_term="firefox"
empty_query="__launcher_empty_probe__"

write_gallery() {
  local gallery_path="$1"
  local image_path
  local image_name
  local rel_image_path

  {
    cat <<'EOF'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Launcher Matrix</title>
  <style>
    :root {
      color-scheme: dark;
      --bg: #111318;
      --panel: #1a1f29;
      --border: #2b3342;
      --text: #e6ebf2;
      --muted: #9aa6b2;
      --accent: #7aa2ff;
    }
    body {
      margin: 0;
      padding: 24px;
      background: var(--bg);
      color: var(--text);
      font: 14px/1.5 system-ui, sans-serif;
    }
    h1 {
      margin: 0 0 12px;
    }
    p {
      margin: 0 0 18px;
      color: var(--muted);
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 16px;
    }
    .card {
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 14px;
      overflow: hidden;
    }
    .card a {
      display: block;
      color: inherit;
      text-decoration: none;
    }
    .card img {
      display: block;
      width: 100%;
      height: auto;
      background: #0b0d12;
    }
    .meta {
      padding: 10px 12px 12px;
    }
    .name {
      font-weight: 600;
      margin-bottom: 4px;
    }
    .path {
      color: var(--muted);
      font-size: 12px;
      word-break: break-all;
    }
  </style>
</head>
<body>
  <h1>Launcher Matrix</h1>
  <p>Generated by <code>capture-launcher-matrix.sh</code>. Click any image to open the full file.</p>
  <div class="grid">
EOF

    while IFS= read -r image_path; do
      rel_image_path="${image_path#${output_dir}/}"
      image_name="$(basename "${image_path}")"
      printf '    <div class="card">\n'
      printf '      <a href="%s">\n' "${rel_image_path}"
      printf '        <img src="%s" alt="%s">\n' "${rel_image_path}" "${image_name}"
      printf '        <div class="meta">\n'
      printf '          <div class="name">%s</div>\n' "${image_name}"
      printf '          <div class="path">%s</div>\n' "${rel_image_path}"
      printf '        </div>\n'
      printf '      </a>\n'
      printf '    </div>\n'
    done < <(find "${output_dir}" -maxdepth 1 -type f -name '*.png' | sort)

    printf '  </div>\n</body>\n</html>\n'
  } > "${gallery_path}"
}

usage() {
  cat <<'EOF'
Usage: capture-launcher-matrix.sh [--id INSTANCE_ID] [--output-dir DIR] [--delay SECONDS] [--crop monitor|usable] [--workspace current|auto|NAME] [--query TERM] [--empty-query TERM]

Capture a focused launcher artifact set for manual review.
This produces review artifacts for key launcher states, not PASS/WARN/FAIL results.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id)
      instance_id="${2:-}"
      shift 2
      ;;
    --output-dir)
      output_dir="${2:-}"
      shift 2
      ;;
    --delay)
      delay_seconds="${2:-}"
      shift 2
      ;;
    --crop)
      crop_mode="${2:-}"
      shift 2
      ;;
    --workspace)
      workspace_target="${2:-}"
      shift 2
      ;;
    --query)
      query_term="${2:-}"
      shift 2
      ;;
    --empty-query)
      empty_query="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "${output_dir}"

launcher_args=()
if [[ -n "${instance_id}" ]]; then
  launcher_args+=(--id "${instance_id}")
fi

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode drun \
  --state home \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/drun-home.png"

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode drun \
  --state query \
  --query "${query_term}" \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/drun-query.png"

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode drun \
  --state category \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/drun-category.png"

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode files \
  --state empty \
  --query "${empty_query}" \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/files-empty.png"

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode system \
  --state home \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/system-home.png"

write_gallery "${output_dir}/index.html"

printf '[INFO] Saved launcher review artifacts to %s\n' "${output_dir}"
