#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

instance_id=""
viewport_preset=""
output_dir="/tmp/launcher-matrix"
delay_seconds="1.2"
crop_mode="hud"
workspace_target="auto"
query_term="firefox"
empty_query="__launcher_empty_probe__"

source "${script_dir}/gallery-lib.sh"

write_gallery() {
  local output_dir="$1"
  local title="Launcher Matrix"
  local script_name="capture-launcher-matrix.sh"
  local gallery_path="${output_dir}/index.html"
  local baseline_dir="${output_dir}/baselines"

  {
    cat <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
EOF
    render_gallery_css
    cat <<EOF
</head>
<body>

<div id="lightbox" onclick="if(event.target === this) closeLightbox()">
  <span class="lightbox-close" onclick="closeLightbox()">&times;</span>
  <div class="lightbox-nav">
    <button onclick="navigateLightbox(-1)">&lsaquo;</button>
    <button onclick="navigateLightbox(1)">&rsaquo;</button>
  </div>
  <img src="" alt="Lightbox">
</div>

<header>
  <div class="title-area">
    <h1>${title}</h1>
    <p>Generated by <code>${script_name}</code></p>
  </div>
  
  <div class="progress-container">
    <span class="progress-text">0 / 0 reviewed (0%)</span>
    <div class="progress-bar"><div class="progress-fill"></div></div>
    <button class="btn" onclick="exportReport()">Export PR Report</button>
  </div>

  <div class="controls">
    <button id="diffFilter" class="btn" onclick="toggleDiffFilter(this)">Filter by Diff</button>
    <input type="text" id="filterInput" placeholder="Filter by filename..." oninput="filterCards()">
  </div>
</header>

<main>
  <div class="grid">
EOF

    while IFS= read -r image_path; do
      rel_image_path="${image_path#${output_dir}/}"
      image_name="$(basename "${image_path}")"
      local baseline_path=""
      [[ -f "${baseline_dir}/${image_name}" ]] && baseline_path="baselines/${image_name}"
      
      # Extract state/mode for repro
      # e.g. drun-home.png
      local state_info="${image_name%.png}"
      local repro="./scripts/capture-launcher-matrix.sh"
      if [[ "${state_info}" == *"-query" ]]; then
         repro="./scripts/capture-launcher-matrix.sh --query ${query_term}"
      fi

      render_card "${rel_image_path}" "${image_name}" "${baseline_path}" "${repro}"
    done < <(find "${output_dir}" -maxdepth 1 -type f -name '*.png' | sort)

    cat <<EOF
  </div>
</main>
EOF
    render_gallery_js
    printf '</body></html>\n'
  } > "${gallery_path}"
}


usage() {
  cat <<'EOF'
Usage: capture-launcher-matrix.sh [--id INSTANCE_ID] [--preset portrait|laptop|wide] [--output-dir DIR] [--delay SECONDS] [--crop hud|monitor|usable] [--workspace current|auto|NAME] [--query TERM] [--empty-query TERM]

Capture a focused launcher artifact set for manual review.
This produces review artifacts for key launcher states, not PASS/WARN/FAIL results.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id)
      instance_id="${2:-}"
      shift 2
      ;;
    --preset)
      viewport_preset="${2:-}"
      shift 2
      ;;
    --output-dir)
      output_dir="${2:-}"
      shift 2
      ;;
    --delay)
      delay_seconds="${2:-}"
      shift 2
      ;;
    --crop)
      crop_mode="${2:-}"
      shift 2
      ;;
    --workspace)
      workspace_target="${2:-}"
      shift 2
      ;;
    --query)
      query_term="${2:-}"
      shift 2
      ;;
    --empty-query)
      empty_query="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

viewport_args=()
if [[ -n "${viewport_preset}" ]]; then
  case "${viewport_preset}" in
    portrait)
      viewport_args+=(--width 430 --height 932)
      ;;
    laptop)
      viewport_args+=(--width 1280 --height 800)
      ;;
    wide)
      viewport_args+=(--width 1600 --height 900)
      ;;
    *)
      printf 'Unknown preset: %s\n' "${viewport_preset}" >&2
      exit 2
      ;;
  esac
fi

mkdir -p "${output_dir}"

launcher_args=()
if [[ -n "${instance_id}" ]]; then
  launcher_args+=(--id "${instance_id}")
fi
launcher_args+=("${viewport_args[@]}")

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode drun \
  --state home \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/drun-home.png"

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode drun \
  --state query \
  --query "${query_term}" \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/drun-query.png"

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode drun \
  --state category \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/drun-category.png" \
  || printf '[INFO] Skipped drun-category capture because no non-All category was available.\n'

if ! bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode files \
  --state empty \
  --query "${empty_query}" \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/files-empty.png"; then
  printf '[INFO] Files empty-state capture did not settle; retrying with files home fallback.\n'
  bash "${script_dir}/capture-launcher-viewport.sh" \
    "${launcher_args[@]}" \
    --mode files \
    --state home \
    --delay "${delay_seconds}" \
    --crop "${crop_mode}" \
    --workspace "${workspace_target}" \
    --output "${output_dir}/files-empty.png"
fi

bash "${script_dir}/capture-launcher-viewport.sh" \
  "${launcher_args[@]}" \
  --mode system \
  --state home \
  --delay "${delay_seconds}" \
  --crop "${crop_mode}" \
  --workspace "${workspace_target}" \
  --output "${output_dir}/system-home.png"

write_gallery "${output_dir}"

if [[ -n "${viewport_preset}" ]]; then
  printf '[INFO] Saved launcher review artifacts for the %s preset to %s\n' "${viewport_preset}" "${output_dir}"
else
  printf '[INFO] Saved launcher review artifacts to %s\n' "${output_dir}"
fi
