#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
tmp_root="${TMPDIR:-/tmp}"

instance_id=""
viewport_preset="portrait"
output_dir="${tmp_root}/settings-matrix"
delay_seconds="4"
scroll_y="0"
workspace_target="auto"
default_tabs=(
  "launcher"
  "launcher-search"
  "launcher-web"
  "launcher-modes"
  "launcher-runtime"
  "ai"
  "wallpaper"
  "bar-widgets"
  "bars"
  "system"
  "plugins"
  "theme"
  "hotkeys"
  "time-weather"
)
tabs=()

usage() {
  cat <<'EOF'
Usage: capture-settings-matrix.sh [--preset portrait|laptop|wide] [--output-dir DIR] [--delay SECONDS] [--scroll-y PX] [--workspace current|auto|NAME] [--tab TAB_ID]

Capture the high-risk settings tabs for a standard viewport preset.
This produces review artifacts for manual inspection, not PASS/WARN/FAIL results.
Repeat `--tab` to capture only specific settings tabs.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id)
      instance_id="${2:-}"
      shift 2
      ;;
    --preset)
      viewport_preset="${2:-}"
      shift 2
      ;;
    --output-dir)
      output_dir="${2:-}"
      shift 2
      ;;
    --delay)
      delay_seconds="${2:-}"
      shift 2
      ;;
    --scroll-y)
      scroll_y="${2:-}"
      shift 2
      ;;
    --workspace)
      workspace_target="${2:-}"
      shift 2
      ;;
    --tab)
      tabs+=("${2:-}")
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if (( ${#tabs[@]} == 0 )); then
  tabs=("${default_tabs[@]}")
fi

for tab in "${tabs[@]}"; do
  case "${tab}" in
    launcher|launcher-search|launcher-web|launcher-modes|launcher-runtime|ai|wallpaper|bar-widgets|bars|system|plugins|theme|hotkeys|time-weather)
      ;;
    *)
      printf 'Unknown settings tab: %s\n' "${tab}" >&2
      exit 2
      ;;
  esac
done

case "${viewport_preset}" in
  portrait)
    width=430
    height=932
    ;;
  laptop)
    width=1280
    height=800
    ;;
  wide)
    width=1600
    height=900
    ;;
  *)
    printf 'Unknown preset: %s\n' "${viewport_preset}" >&2
    exit 2
    ;;
esac

mkdir -p "${output_dir}"

viewport_args=()
if [[ -n "${instance_id}" ]]; then
  viewport_args+=(--id "${instance_id}")
fi

source "${script_dir}/gallery-lib.sh"

write_gallery() {
  local output_dir="$1"
  local title="Settings Matrix"
  local script_name="capture-settings-matrix.sh"
  local gallery_path="${output_dir}/index.html"
  local baseline_dir="${output_dir}/baselines"

  {
    cat <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
EOF
    render_gallery_css
    cat <<EOF
</head>
<body>

<div id="lightbox" onclick="if(event.target === this) closeLightbox()">
  <span class="lightbox-close" onclick="closeLightbox()">&times;</span>
  <div class="lightbox-nav">
    <button onclick="navigateLightbox(-1)">&lsaquo;</button>
    <button onclick="navigateLightbox(1)">&rsaquo;</button>
  </div>
  <img src="" alt="Lightbox">
</div>

<header>
  <div class="title-area">
    <h1>${title}</h1>
    <p>Generated by <code>${script_name}</code></p>
  </div>
  
  <div class="progress-container">
    <span class="progress-text">0 / 0 reviewed (0%)</span>
    <div class="progress-bar"><div class="progress-fill"></div></div>
    <button class="btn" onclick="exportReport()">Export PR Report</button>
  </div>

  <div class="controls">
    <button id="diffFilter" class="btn" onclick="toggleDiffFilter(this)">Filter by Diff</button>
    <input type="text" id="filterInput" placeholder="Filter by filename..." oninput="filterCards()">
  </div>
</header>

<main>
  <div class="grid">
EOF

    while IFS= read -r image_path; do
      rel_image_path="${image_path#${output_dir}/}"
      image_name="$(basename "${image_path}")"
      local baseline_path=""
      [[ -f "${baseline_dir}/${image_name}" ]] && baseline_path="baselines/${image_name}"
      
      # portrait-launcher.png -> launcher
      local tab="${image_name#*-}"
      tab="${tab%.png}"
      local repro="./scripts/capture-settings-matrix.sh --tab ${tab}"

      render_card "${rel_image_path}" "${image_name}" "${baseline_path}" "${repro}"
    done < <(find "${output_dir}" -maxdepth 1 -type f -name '*.png' | sort)

    cat <<EOF
  </div>
</main>
EOF
    render_gallery_js
    printf '</body></html>\n'
  } > "${gallery_path}"
}

for tab in "${tabs[@]}"; do
  bash "${script_dir}/capture-settings-viewport.sh" \
    "${viewport_args[@]}" \
    --width "${width}" \
    --height "${height}" \
    --delay "${delay_seconds}" \
    --scroll-y "${scroll_y}" \
    --workspace "${workspace_target}" \
    --tab "${tab}" \
    --output "${output_dir}/${viewport_preset}-${tab}.png"
done

write_gallery "${output_dir}"

printf '[INFO] Saved settings review artifacts for the %s matrix to %s\n' "${viewport_preset}" "${output_dir}"
printf '[INFO] Saved review gallery to %s/index.html\n' "${output_dir}"
