#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
config_dir="${QS_CONFIG_DIR:-${script_dir}/../src}"
launcher_qml="${config_dir}/launcher/Launcher.qml"
launcher_content_panel_qml="${config_dir}/launcher/LauncherContentPanel.qml"
launcher_ipc_handler_qml="${config_dir}/launcher/LauncherIpcHandler.qml"
launcher_diag_js="${config_dir}/launcher/LauncherDiagnostics.js"
launcher_executor_js="${config_dir}/launcher/LauncherExecutor.js"
launcher_parser_js="${config_dir}/launcher/LauncherFileParser.js"
launcher_text_js="${config_dir}/launcher/LauncherTextHelpers.js"
launcher_delegate_qml="${config_dir}/launcher/LauncherResultDelegate.qml"
config_qml="${config_dir}/services/Config.qml"
config_persistence_js="${config_dir}/services/config/ConfigPersistence.js"
launcher_domain_js="${config_dir}/services/config/domains/launcher.js"
config_launcher_js="${config_dir}/services/config/ConfigLauncher.js"
launcher_settings_qml="${config_dir}/features/settings/components/tabs/ShellLauncherSection.qml"
launcher_search_settings_qml="${config_dir}/features/settings/components/tabs/LauncherSearchSection.qml"
launcher_helpers_js="${config_dir}/features/settings/components/tabs/ShellCoreHelpers.js"

violations=()
source "${script_dir}/check-helpers.sh"

require_literal "$config_qml" 'property string launcherFileSearchRoot: "~"' "launcher file search root config"
require_literal "$config_qml" 'property bool launcherFileShowHidden: false' "launcher file hidden toggle config"
require_literal "$config_qml" 'property string launcherFileOpener: "xdg-open"' "launcher file opener config"
require_literal "$launcher_domain_js" '["fileSearchRoot", "launcherFileSearchRoot"]' "launcher file root persistence"
require_literal "$launcher_domain_js" '["fileShowHidden", "launcherFileShowHidden"]' "launcher file hidden persistence"
require_literal "$launcher_domain_js" '["fileOpener", "launcherFileOpener"]' "launcher file opener persistence"
require_literal "$config_launcher_js" 'config.launcherFileSearchRoot = normalizeLauncherPath(launcher.fileSearchRoot, "~");' "launcher file root normalization"
require_literal "$config_launcher_js" 'config.launcherFileShowHidden = asBool(launcher.fileShowHidden, false);' "launcher file hidden normalization"
require_literal "$config_launcher_js" 'config.launcherFileOpener = normalizeLauncherCommand(launcher.fileOpener, "xdg-open");' "launcher file opener normalization"
require_literal "$launcher_helpers_js" 'Config.launcherFileSearchRoot = "~";' "launcher file root reset"
require_literal "$launcher_helpers_js" 'Config.launcherFileShowHidden = false;' "launcher file hidden reset"
require_literal "$launcher_helpers_js" 'Config.launcherFileOpener = "xdg-open";' "launcher file opener reset"
require_literal "$launcher_settings_qml" 'label: "Default Search Directory"' "launcher settings file root row" "$launcher_search_settings_qml"
require_literal "$launcher_settings_qml" 'configKey: "launcherFileShowHidden"' "launcher settings hidden toggle row" "$launcher_search_settings_qml"
require_literal "$launcher_settings_qml" 'label: "File Opener"' "launcher settings file opener row" "$launcher_search_settings_qml"
require_literal "$launcher_qml" 'readonly property string fileSearchRootResolved: resolveFileSearchRoot(fileSearchRootSetting)' "launcher resolved file root property"
require_literal "$launcher_qml" 'readonly property bool fileSearchShowHidden: diagnosticFileSearchShowHiddenOverrideActive' "launcher hidden toggle property"
require_literal "$launcher_qml" 'readonly property string fileOpenerCommand: {' "launcher file opener property"
require_literal "$launcher_qml" 'property string diagnosticFileSearchRootOverride: ""' "launcher file root diagnostic override"
require_literal "$launcher_qml" 'function applyFileSearchFailure(errorText, fallbackMessage) {' "launcher file failure helper"
require_literal "$launcher_qml" 'FileOps.openFileItem(item, _fileOpsCtx);' "launcher file opener helper"
require_literal "$launcher_qml" 'FileOps.revealFileInManager(item, _fileOpsCtx);' "launcher file reveal helper"
require_literal "$launcher_qml" 'return FileOps.fileContextMenuModel(item, _fileOpsCtx);' "launcher file context menu helper"
require_literal "$launcher_content_panel_qml" 'ContextMenu {' "launcher file context menu component"
require_literal "$launcher_content_panel_qml" 'fileResultContextMenu.model = menuModel;' "launcher file context menu wiring"
require_literal "$launcher_qml" 'if (fileSearchShowHidden)' "launcher fd hidden toggle handling"
require_literal "$launcher_qml" 'applyFileSearchFailure(errorText, "File search failed");' "launcher file search error handling"
require_literal "$launcher_ipc_handler_qml" 'function diagnosticSetFileSearchRoot(rootValue: string): string {' "launcher file root IPC override"
require_literal "$launcher_ipc_handler_qml" 'function diagnosticSetFileShowHidden(value: string): string {' "launcher file hidden IPC override"
require_literal "$launcher_ipc_handler_qml" 'function diagnosticSetFileOpener(command: string): string {' "launcher file opener IPC override"
require_literal "$launcher_ipc_handler_qml" 'function diagnosticClearFileOverrides(): string {' "launcher file override reset IPC"
require_literal "$launcher_ipc_handler_qml" 'function diagnosticExecuteEmptyPrimary(): string {' "launcher file empty primary IPC"
require_literal "$launcher_ipc_handler_qml" 'function diagnosticExecuteSelection(): string {' "launcher file selection IPC"
require_literal "$launcher_diag_js" 'fileSearchRootResolved: String(props.fileSearchRootResolved || ""),' "launcher state includes file root"
require_literal "$launcher_diag_js" 'fileSearchShowHidden: props.fileSearchShowHidden === true,' "launcher state includes hidden toggle"
require_literal "$launcher_executor_js" 'actions.openFileItem(item);' "launcher executor file open helper"
require_literal "$launcher_executor_js" 'actions.openDirectoryPath(actions.fileSearchRootResolved);' "launcher executor open configured root"
require_literal "$launcher_executor_js" 'actions.openDirectoryPath(target);' "launcher executor secondary open path"
require_literal "$launcher_delegate_qml" 'signal secondaryActionRequested(var sourceItem, real localX, real localY)' "launcher delegate secondary action signal"
require_literal "$launcher_parser_js" 'function iconForFile(name, extension, kind) {' "launcher file icon classifier"
require_literal "$launcher_parser_js" 'icon: iconForFile(name, extension, kind)' "launcher parser assigns file icon"
require_literal "$launcher_text_js" 'return "Start typing to search " + _humanFileRootLabel(fileRootLabel, "Home");' "launcher text helper file root title"

report_violations "Launcher file search check"
