#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
config_dir="${QS_CONFIG_DIR:-${script_dir}/../src}"

launcher_qml="${config_dir}/launcher/Launcher.qml"
launcher_content_panel_qml="${config_dir}/launcher/LauncherContentPanel.qml"
launcher_sidebar_qml="${config_dir}/launcher/LauncherSidebar.qml"
launcher_search_field_qml="${config_dir}/launcher/LauncherSearchField.qml"
launcher_legend_qml="${config_dir}/launcher/LauncherActionLegend.qml"
launcher_prefix_strip_qml="${config_dir}/launcher/LauncherPrefixStrip.qml"
launcher_executor_js="${config_dir}/launcher/LauncherExecutor.js"
launcher_entry_registry_js="${config_dir}/launcher/LauncherEntryRegistry.js"
launcher_system_items_js="${config_dir}/launcher/LauncherSystemItems.js"
launcher_search_js="${config_dir}/launcher/LauncherSearch.js"
launcher_diag_js="${config_dir}/launcher/LauncherDiagnostics.js"
launcher_metrics_js="${config_dir}/launcher/LauncherMetrics.js"
launcher_metrics_box_qml="${config_dir}/launcher/LauncherMetricsBox.qml"
launcher_text_helpers_js="${config_dir}/launcher/LauncherTextHelpers.js"
settings_hub_qml="${config_dir}/features/settings/SettingsHub.qml"
launcher_settings_qml="${config_dir}/features/settings/components/tabs/ShellLauncherSection.qml"
launcher_modes_settings_qml="${config_dir}/features/settings/components/tabs/LauncherModesSection.qml"
launcher_helpers_js="${config_dir}/features/settings/components/tabs/ShellCoreHelpers.js"
config_qml="${config_dir}/services/Config.qml"
config_persistence_js="${config_dir}/services/config/ConfigPersistence.js"
launcher_domain_js="${config_dir}/services/config/domains/launcher.js"
config_launcher_js="${config_dir}/services/config/ConfigLauncher.js"

violations=()
source "${script_dir}/check-helpers.sh"

# Config/state wiring
require_literal "$config_qml" 'property var launcherPrimaryModes: ["drun", "window", "files", "ai", "system"]' "primary sidebar config property"
require_literal "$config_qml" 'property bool launcherDrunCategoryFiltersEnabled: false' "drun category filter enable config property"
require_literal "$launcher_domain_js" '["primaryModes", "launcherPrimaryModes"]' "primary sidebar config persistence"
require_literal "$launcher_domain_js" '["drunCategoryFiltersEnabled", "launcherDrunCategoryFiltersEnabled"]' "drun category filter enable config persistence"
require_literal "$config_launcher_js" 'function normalizePrimaryModeList(list, enabledModes, fallbackList) {' "primary mode normalization helper"
require_literal "$config_launcher_js" 'config.launcherPrimaryModes = normalizePrimaryModeList(launcher.primaryModes, config.launcherEnabledModes, fallbackPrimaryModes);' "primary mode config application"
require_literal "$launcher_helpers_js" 'function orderedPrimaryModes(Config, CompositorAdapter, launcherModes) {' "settings helper ordered primary modes"
require_literal "$launcher_helpers_js" 'function orderedAdvancedModes(Config, CompositorAdapter, launcherModes) {' "settings helper ordered advanced modes"
require_literal "$launcher_helpers_js" 'function disabledLauncherModes(Config, CompositorAdapter, launcherModes) {' "settings helper disabled modes"
require_literal "$launcher_helpers_js" 'preset === "extended" || preset === "core"' "extended preset compatibility"
require_literal "$launcher_helpers_js" 'preset === "all" || preset === "full"' "all preset compatibility"
require_literal "$launcher_helpers_js" 'presetModes = ["drun", "window", "files", "ai", "system", "settings", "run", "ssh", "web"];' "extended preset mode set"

# Metrics core
require_literal "$launcher_qml" 'property alias launcherMetrics: controller.launcherMetrics' "launcher metrics state property"
require_literal "$launcher_qml" 'readonly property string filesCacheStatsLabel: {' "files cache stats label property"
require_literal "$launcher_qml" 'function recordFilterMetric(durationMs) {' "filter metric recorder"
require_literal "$launcher_qml" 'function recordFilesBackendLoad(backend, durationMs) {' "files backend metric recorder"
require_literal "$launcher_qml" 'function recordFilesBackendResolveMetric(durationMs) {' "files backend resolve metric recorder"
require_literal "$launcher_qml" 'showTransientNotice("Files backend re-detected: " + backend, 2600);' "files backend redetect feedback notice"
require_literal "$launcher_qml" 'showTransientNotice("Launcher diagnostics reset", 2200);' "launcher diagnostic reset feedback notice"
require_literal "$launcher_metrics_js" 'function freshMetrics() {' "metrics fresh state helper"
require_literal "$launcher_metrics_js" 'function recordFilesBackendLoad(metrics, backend, durationMs) {' "metrics files backend load helper"
require_literal "$launcher_metrics_js" 'function recordFilesBackendResolveMetric(metrics, durationMs) {' "metrics backend resolve helper"
require_literal "$launcher_diag_js" 'function filesBackendStatusObject(props) {' "files backend diagnostics helper"
require_literal "$launcher_metrics_box_qml" '"filter avg " + (root.metrics.avgFilterMs || 0) + "ms"' "runtime metrics filter average display"
require_literal "$launcher_diag_js" 'filesResolveAvgMs: resolveAvgMs,' "runtime metrics resolve latency in diagnostics payload"

# Search/ranking path
require_literal "$launcher_search_js" 'function fuzzyMatchLower(s, p) {' "lowercased fuzzy matcher"
require_literal "$launcher_search_js" 'function ensureItemRankCache(item) {' "rank cache preparation helper"
require_literal "$launcher_search_js" 'item._categoryKeywordsLower = (category + " " + keywords).trim();' "category keywords cache field"
require_literal "$launcher_search_js" 'function rankItem(item, clean, cleanLower, mode, weights) {' "rank function with precomputed query"
require_literal "$launcher_qml" 'category: Config.launcherScoreCategoryWeight' "search category weight wiring"
forbid_literal "$launcher_qml" 'function fuzzyMatch(str, pattern) {' "legacy fuzzy matcher signature"

# New launcher UX contract
require_literal "$launcher_qml" 'property bool sidebarOverflowExpanded: false' "sidebar overflow state"
require_literal "$launcher_qml" 'property bool shortcutHelpExpanded: false' "shortcut help state"
require_literal "$launcher_qml" 'readonly property var overflowModes:' "overflow mode list"
require_literal "$launcher_qml" 'readonly property var prefixQuickModes:' "prefix quick mode list"
require_literal "$launcher_content_panel_qml" 'statusText: launcher.escapeStatusText' "search field escape status binding"
require_literal "$launcher_content_panel_qml" 'LauncherPrefixStrip {' "prefix strip component usage"
require_literal "$launcher_content_panel_qml" 'summaryText: launcher.modeSummaryText' "summary legend binding"
require_literal "$launcher_content_panel_qml" 'helpExpanded: launcher.shortcutHelpExpanded' "legend help state binding"
require_literal "$launcher_qml" 'SU.ipcCall("SettingsHub", "openSetting", tabId, cardTitle || "", labelText || "")' "settings deep-link action"
require_literal "$launcher_sidebar_qml" 'label: root.launcher.sidebarOverflowExpanded ? "Hide More" : "More"' "sidebar more affordance"
require_literal "$launcher_legend_qml" 'text: root.helpExpanded ? "Hide Help" : "Show Help"' "on-demand help toggle"
require_literal "$launcher_search_field_qml" 'property string statusText: ""' "search field status text property"
require_literal "$launcher_prefix_strip_qml" 'text: modeInfo.prefix || ""' "prefix strip prefix label"
require_literal "$launcher_entry_registry_js" 'function buildSystemDestinationItems(actions) {' "system destination registry"
require_literal "$launcher_entry_registry_js" 'function buildCommandPaletteActions(actions) {' "command palette registry"
require_literal "$launcher_system_items_js" 'var items = EntryRegistry.buildSystemDestinationItems(actions);' "system items use shared destination registry"
require_literal "$launcher_executor_js" 'if (String(item.entryKind || "") === "destination")' "executor destination action label override"
require_literal "$launcher_executor_js" 'if (mode === "settings") {' "settings execution path"
require_literal "$launcher_text_helpers_js" 'if (mode === "settings")' "settings empty-state text"

# Settings exposure
require_literal "$launcher_settings_qml" 'title: "Launcher Presets"' "launcher presets card" "$launcher_modes_settings_qml"
require_literal "$launcher_settings_qml" 'label: "Focused"' "focused preset button" "$launcher_modes_settings_qml"
require_literal "$launcher_settings_qml" 'label: "Extended"' "extended preset button" "$launcher_modes_settings_qml"
require_literal "$launcher_settings_qml" 'title: "Primary Sidebar"' "primary sidebar card" "$launcher_modes_settings_qml"
require_literal "$launcher_settings_qml" 'title: "Advanced / Prefix"' "advanced modes card" "$launcher_modes_settings_qml"
require_literal "$launcher_settings_qml" 'title: "Disabled Modes"' "disabled modes card" "$launcher_modes_settings_qml"
require_literal "$settings_hub_qml" 'function openSetting(tabId, cardTitle, settingLabel) {' "settings hub openSetting helper"
require_literal "$settings_hub_qml" 'function openSetting(tabId: string, cardTitle: string, settingLabel: string) {' "settings hub openSetting IPC mapping"

report_violations "Launcher performance check"
