#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
launcher_qml="${script_dir}/../config/launcher/Launcher.qml"
config_qml="${script_dir}/../config/services/Config.qml"
system_tab_qml="${script_dir}/../config/menu/settings/tabs/SystemTab.qml"

violations=()

require_literal() {
  local file="$1"
  local needle="$2"
  local label="$3"
  if ! rg -n -F -- "$needle" "$file" >/dev/null 2>&1; then
    violations+=("${label} missing in ${file}")
  fi
}

forbid_literal() {
  local file="$1"
  local needle="$2"
  local label="$3"
  if rg -n -F -- "$needle" "$file" >/dev/null 2>&1; then
    violations+=("${label} should not be present in ${file}")
  fi
}

require_literal "$launcher_qml" 'filterRuns: 0,' "filter metric counter"
require_literal "$launcher_qml" 'lastFilterMs: 0,' "last filter metric field"
require_literal "$launcher_qml" 'avgFilterMs: 0,' "average filter metric field"
require_literal "$launcher_qml" 'filesFdLoads: 0,' "files fd backend metric field"
require_literal "$launcher_qml" 'filesFindLoads: 0,' "files find backend metric field"
require_literal "$launcher_qml" 'filesFdLastMs: 0,' "files fd last latency metric field"
require_literal "$launcher_qml" 'filesFindLastMs: 0,' "files find last latency metric field"
require_literal "$launcher_qml" 'filesFdAvgMs: 0,' "files fd average latency metric field"
require_literal "$launcher_qml" 'filesFindAvgMs: 0,' "files find average latency metric field"
require_literal "$launcher_qml" 'filesResolveRuns: 0,' "files backend resolve run metric field"
require_literal "$launcher_qml" 'filesResolveLastMs: 0,' "files backend resolve last latency metric field"
require_literal "$launcher_qml" 'filesResolveAvgMs: 0,' "files backend resolve average latency metric field"
require_literal "$launcher_qml" 'property int fileSearchBackendResolvedAt: 0' "files backend resolved timestamp cache field"
require_literal "$launcher_qml" 'readonly property int fileSearchBackendRefreshMs: 180000' "files backend refresh interval field"
require_literal "$launcher_qml" 'readonly property int fileSearchBackendMissRefreshMs: 20000' "files backend miss refresh interval field"
require_literal "$config_qml" 'property real launcherScoreCategoryWeight: 0.7' "category weight config property"
require_literal "$config_qml" 'property bool launcherDrunCategoryFiltersEnabled: true' "drun category filter enable config property"
require_literal "$config_qml" 'launcherDrunCategoryFiltersEnabled = _asBool(launcher.drunCategoryFiltersEnabled, true);' "drun category filter enable config load"
require_literal "$config_qml" 'onLauncherDrunCategoryFiltersEnabledChanged: scheduleSave()' "drun category filter enable config autosave hook"
require_literal "$config_qml" '"drunCategoryFiltersEnabled": launcherDrunCategoryFiltersEnabled,' "drun category filter enable config persistence"
require_literal "$config_qml" 'launcherScoreCategoryWeight = _clampReal(launcher.scoreCategoryWeight, 0.1, 4.0, 0.7);' "category weight config load"
require_literal "$config_qml" 'onLauncherScoreCategoryWeightChanged: scheduleSave()' "category weight config autosave hook"
require_literal "$config_qml" '"scoreCategoryWeight": launcherScoreCategoryWeight' "category weight config persistence"
require_literal "$launcher_qml" 'readonly property string filesCacheStatsLabel: {' "files cache stats label property"
require_literal "$launcher_qml" 'function recordFilterMetric(durationMs) {' "filter metric recorder"
require_literal "$launcher_qml" 'function recordFilesBackendLoad(backend, durationMs) {' "files backend metric recorder"
require_literal "$launcher_qml" 'function recordFilesBackendResolveMetric(durationMs) {' "files backend resolve metric recorder"
require_literal "$launcher_qml" 'function invalidateCommandAvailability(cmd) {' "command availability invalidation helper"
require_literal "$launcher_qml" 'function showTransientNotice(message, durationMs) {' "launcher transient notice helper"
require_literal "$launcher_qml" 'function clearSearchQuery() {' "launcher clear search helper"
require_literal "$launcher_qml" 'function moveSelectionRelative(step) {' "launcher relative selection helper"
require_literal "$launcher_qml" 'property string transientNoticeText: ""' "launcher transient notice property"
require_literal "$launcher_qml" 'property string drunCategoryFilter: ""' "drun category filter state property"
require_literal "$launcher_qml" 'property var drunCategoryOptions: [{ key: "", label: "All", count: 0, hotkey: "0" }]' "drun category options property"
require_literal "$launcher_qml" 'readonly property bool drunCategoryFiltersEnabled: Config.launcherDrunCategoryFiltersEnabled' "drun category filter enable binding"
require_literal "$launcher_qml" 'readonly property string drunCategoryFilterLabel: {' "drun category filter label property"
require_literal "$launcher_qml" 'readonly property string launcherControlHintText: {' "launcher control hint text property"
require_literal "$launcher_qml" 'var resultHint = hasResults ? "↑/↓/Ctrl+P/N/PgUp/PgDn/Home/End: results • " : "";' "launcher control result hint text"
require_literal "$launcher_qml" 'var clearHint = searchText !== "" ? "Ctrl+L/U: clear • " : "";' "launcher control clear hint text"
require_literal "$launcher_qml" 'return resultHint + clearHint + "Enter: run • Esc: close";' "default keyboard hint text with clear action"
require_literal "$launcher_qml" 'return "Alt+←/→/PgUp/PgDn/Home/End/0/Backspace, Ctrl+Tab, or Alt+1..9: categories • " + resultHint + clearHint + "Enter: run • Esc: close";' "drun category keyboard hint text with clear action"
require_literal "$launcher_qml" 'function filesBackendStatusObject() {' "files backend status payload helper"
require_literal "$launcher_qml" 'metrics: ({' "files backend status metrics object"
require_literal "$launcher_qml" 'filesResolveAvgMs: resolveAvgMs,' "files backend status metrics resolve avg field"
require_literal "$launcher_qml" 'filesResolveLastMs: resolveLastMs,' "files backend status metrics resolve last field"
require_literal "$launcher_qml" 'filesFdLoads: filesFdLoads,' "files backend status metrics fd loads field"
require_literal "$launcher_qml" 'filesFindLoads: filesFindLoads,' "files backend status metrics find loads field"
require_literal "$launcher_qml" 'cache: ({' "files backend status cache object"
require_literal "$launcher_qml" 'hits: fileCacheHits,' "files backend status cache hits field"
require_literal "$launcher_qml" 'misses: fileCacheMisses,' "files backend status cache misses field"
require_literal "$launcher_qml" 'function forceRedetectFileSearchBackend(announce, callback) {' "manual files backend redetect helper"
require_literal "$launcher_qml" 'function diagnosticReset() {' "launcher diagnostic reset helper"
require_literal "$launcher_qml" 'function redetectFilesBackend() { launcherRoot.forceRedetectFileSearchBackend(true, function(_) {}); }' "files backend redetect IPC action"
require_literal "$launcher_qml" 'function diagnosticReset() { launcherRoot.diagnosticReset(); }' "launcher diagnostic reset IPC action"
require_literal "$launcher_qml" 'function filesBackendStatus() { return JSON.stringify(launcherRoot.filesBackendStatusObject()); }' "files backend status IPC action"
require_literal "$launcher_qml" 'recordFilterMetric(Date.now() - startedAt);' "filter metric recording call"
require_literal "$launcher_qml" 'recordFilesBackendLoad(backend, tookMs);' "files backend metric recording call"
require_literal "$launcher_qml" 'recordFilesBackendResolveMetric(Date.now() - startedAt);' "files backend resolve metric recording call"
require_literal "$launcher_qml" 'invalidateCommandAvailability("fd");' "files backend fd cache invalidation call"
require_literal "$launcher_qml" 'invalidateCommandAvailability("find");' "files backend find cache invalidation call"
require_literal "$launcher_qml" 'showTransientNotice("Files backend re-detected: " + backend, 2600);' "files backend redetect feedback notice"
require_literal "$launcher_qml" 'showTransientNotice("Launcher diagnostics reset", 2200);' "launcher diagnostic reset feedback notice"
require_literal "$launcher_qml" 'function fuzzyMatchLower(s, p) {' "lowercased fuzzy matcher"
require_literal "$launcher_qml" 'function ensureItemRankCache(item) {' "rank cache preparation helper"
require_literal "$launcher_qml" 'item._categoryTokens = tokens;' "rank cache category token extraction"
require_literal "$launcher_qml" 'item._primaryCategoryKey = tokens.length > 0 ? tokens[0] : "";' "rank cache primary category key"
require_literal "$launcher_qml" 'item._categoryKeywordsLower = (category + " " + keywords).trim();' "category keywords cache field"
require_literal "$launcher_qml" 'function refreshDrunCategoryOptions(apps) {' "drun category options refresh helper"
require_literal "$launcher_qml" 'if (!drunCategoryFiltersEnabled) {' "drun category options refresh disabled guard"
require_literal "$launcher_qml" 'function setDrunCategoryFilter(categoryKey) {' "drun category filter setter"
require_literal "$launcher_qml" 'if (!drunCategoryFiltersEnabled) {' "drun category setter disabled guard"
require_literal "$launcher_qml" 'function cycleDrunCategoryFilter(step) {' "drun category filter cycling helper"
require_literal "$launcher_qml" 'if (!drunCategoryFiltersEnabled || mode !== "drun" || drunCategoryOptions.length <= 1)' "drun category cycle disabled guard"
require_literal "$launcher_qml" 'function selectDrunCategorySlot(slot) {' "drun category filter slot helper"
require_literal "$launcher_qml" 'if (!drunCategoryFiltersEnabled || mode !== "drun" || slot < 1)' "drun category slot disabled guard"
require_literal "$launcher_qml" 'function pageSelection(step) {' "selection paging helper"
require_literal "$launcher_qml" 'var pageSize = Math.max(5, Math.min(12, Math.round(hudBox.height / 72)));' "selection paging size calculation"
require_literal "$launcher_qml" 'function rankItem(item, clean, cleanLower) {' "rank function with precomputed query"
require_literal "$launcher_qml" 'ensureItemRankCache(item);' "rank cache usage"
require_literal "$launcher_qml" 'var categoryScore = mode === "drun" ? (fuzzyMatchLower(item._categoryKeywordsLower, cleanLower) * Config.launcherScoreCategoryWeight) : 0;' "rank drun-only category/keywords score weighting"
require_literal "$launcher_qml" 'function compareLauncherItemsAlpha(a, b) {' "deterministic launcher item alpha comparator"
require_literal "$launcher_qml" 'return compareLauncherItemsAlpha(a, b);' "deterministic tie-breaker usage"
require_literal "$launcher_qml" 'var cleanLower = clean.toLowerCase();' "single query lowercase preparation"
require_literal "$launcher_qml" 'fuzzyMatchLower(item._nameLower, cleanLower)' "rank uses lowered matcher"
require_literal "$launcher_qml" 'if (mode === "drun" && drunCategoryFilter !== "" && !itemMatchesDrunCategory(item, drunCategoryFilter))' "drun category filter gating in result list"
require_literal "$launcher_qml" 'recent.sort(function(a, b) {' "recent apps deterministic ordering sort"
require_literal "$launcher_qml" 'if ((b._recent || 0) !== (a._recent || 0))' "recent apps timestamp-first ordering"
require_literal "$launcher_qml" 'launcherRoot.showLauncherHome && launcherRoot.drunCategoryFiltersEnabled && launcherRoot.mode === "drun" && launcherRoot.drunCategoryOptions.length > 1' "drun category chip visibility guard"
require_literal "$launcher_qml" 'launcherRoot.drunCategoryFiltersEnabled && launcherRoot.mode === "drun" && (event.modifiers & Qt.AltModifier) && !(event.modifiers & Qt.ControlModifier)' "drun category keyboard handling branch"
require_literal "$launcher_qml" 'if (event.key === Qt.Key_Left) {' "drun category keyboard left cycling"
require_literal "$launcher_qml" 'if (launcherRoot.cycleDrunCategoryFilter(-1))' "drun category left cycle action"
require_literal "$launcher_qml" 'if (launcherRoot.cycleDrunCategoryFilter(1))' "drun category right cycle action"
require_literal "$launcher_qml" 'else if (event.key === Qt.Key_PageUp) {' "drun category page-up action branch"
require_literal "$launcher_qml" 'else if (event.key === Qt.Key_PageDown) {' "drun category page-down action branch"
require_literal "$launcher_qml" 'function jumpDrunCategoryBoundary(toEnd) {' "drun category boundary helper"
require_literal "$launcher_qml" 'else if (event.key === Qt.Key_Home) {' "drun category home action branch"
require_literal "$launcher_qml" 'if (launcherRoot.jumpDrunCategoryBoundary(false))' "drun category home action"
require_literal "$launcher_qml" 'else if (event.key === Qt.Key_End) {' "drun category end action branch"
require_literal "$launcher_qml" 'if (launcherRoot.jumpDrunCategoryBoundary(true))' "drun category end action"
require_literal "$launcher_qml" 'else if (event.key === Qt.Key_0 || event.key === Qt.Key_Backspace) {' "drun category clear action branch"
require_literal "$launcher_qml" 'if (launcherRoot.setDrunCategoryFilter(""))' "drun category clear shortcut"
require_literal "$launcher_qml" 'if (categorySlot > 0 && launcherRoot.selectDrunCategorySlot(categorySlot))' "drun category numeric slot shortcut"
require_literal "$launcher_qml" 'launcherRoot.drunCategoryFiltersEnabled && launcherRoot.mode === "drun" && launcherRoot.showLauncherHome && (event.modifiers & Qt.ControlModifier) && event.key === Qt.Key_Tab' "drun category ctrl+tab keyboard handling branch"
require_literal "$launcher_qml" 'var direction = (event.modifiers & Qt.ShiftModifier) ? -1 : 1;' "drun category ctrl+tab direction handling"
require_literal "$launcher_qml" 'if (launcherRoot.cycleDrunCategoryFilter(direction))' "drun category ctrl+tab cycle action"
require_literal "$launcher_qml" '+ " • filter avg " + (launcherRoot.launcherMetrics.avgFilterMs || 0) + "ms"' "runtime metrics filter average display"
require_literal "$launcher_qml" '+ " / last " + (launcherRoot.launcherMetrics.lastFilterMs || 0) + "ms"' "runtime metrics filter last display"
require_literal "$launcher_qml" '+ " • fd/find " + (launcherRoot.launcherMetrics.filesFdLoads || 0) + "/"' "runtime metrics files backend counter display"
require_literal "$launcher_qml" '+ " • fd " + (launcherRoot.launcherMetrics.filesFdAvgMs || 0) + "/" + (launcherRoot.launcherMetrics.filesFdLastMs || 0) + "ms"' "runtime metrics fd latency display"
require_literal "$launcher_qml" '+ " • find " + (launcherRoot.launcherMetrics.filesFindAvgMs || 0) + "/" + (launcherRoot.launcherMetrics.filesFindLastMs || 0) + "ms"' "runtime metrics find latency display"
require_literal "$launcher_qml" '+ " • resolve " + (launcherRoot.launcherMetrics.filesResolveAvgMs || 0) + "/" + (launcherRoot.launcherMetrics.filesResolveLastMs || 0) + "ms"' "runtime metrics resolve latency display"
require_literal "$launcher_qml" '+ (launcherRoot.mode === "files" ? (" • cache " + launcherRoot.filesCacheStatsLabel) : "")' "runtime metrics files cache stats display"
require_literal "$system_tab_qml" 'label: "Re-detect Files Backend"' "settings button label for files backend redetect"
require_literal "$system_tab_qml" 'onClicked: Quickshell.execDetached(["quickshell", "ipc", "call", "Launcher", "redetectFilesBackend"])' "settings redetect files backend action binding"
require_literal "$system_tab_qml" 'label: "Launcher Diagnostic Reset"' "settings button label for launcher diagnostic reset"
require_literal "$system_tab_qml" 'onClicked: Quickshell.execDetached(["quickshell", "ipc", "call", "Launcher", "diagnosticReset"])' "settings launcher diagnostic reset action binding"
require_literal "$system_tab_qml" 'label: "Category/Keywords Weight"' "settings category keywords weight slider label"
require_literal "$system_tab_qml" 'value: Config.launcherScoreCategoryWeight' "settings category keywords weight slider binding"
require_literal "$system_tab_qml" 'onMoved: v => Config.launcherScoreCategoryWeight = v' "settings category keywords weight slider action"
require_literal "$system_tab_qml" 'label: "App Category Filters"' "settings app category filters toggle label"
require_literal "$system_tab_qml" 'configKey: "launcherDrunCategoryFiltersEnabled"' "settings app category filters toggle binding"
require_literal "$system_tab_qml" 'Config.launcherDrunCategoryFiltersEnabled = true;' "settings app category filters reset default"
forbid_literal "$launcher_qml" 'function fuzzyMatch(str, pattern) {' "legacy fuzzy matcher signature"

if (( ${#violations[@]} > 0 )); then
  printf '%s\n' "Launcher performance check failed:" >&2
  printf '  - %s\n' "${violations[@]}" >&2
  exit 1
fi

printf '%s\n' "Launcher performance check passed."
