# This file is auto-generated by scripts/vscode/vscodefetch.sh
# Do not edit manually - run the script to update extensions

{}: [
  {
    name = "ansible";
    publisher = "redhat";
    sha256 = "sha256-iBAlDqi7u/srkgBBLha/JCHZnpccz37BdZ7zVJVfJYY=";
    version = "26.1.3";
  },
  {
    name = "biome";
    publisher = "biomejs";
    sha256 = "sha256-TLm2ppAyZoCHNg3RpEFwUr/C04bkI62AK4kNS4R/j2U=";
    version = "2025.11.271431";
  },
  {
    name = "chatgpt";
    publisher = "openai";
    sha256 = "sha256-s4DULSFqETivP06BcxcQrNwM0NmzEwqkuRsPs4QBM/M=";
    version = "0.5.67";
  },
  {
    name = "claude-code";
    publisher = "anthropic";
    sha256 = "sha256-8r2/bF5zkq4LkMKvI5YcBMaaMzgWAIezdIwTMQQBHsM=";
    version = "2.1.20";
  },
  {
    name = "explorer";
    publisher = "vitest";
    sha256 = "sha256-pcJgVYXGpkK2SGGvEF9aiRmk3kKte321qP/17awo5MU=";
    version = "1.38.1";
  },
  {
    name = "gemini-cli-vscode-ide-companion";
    publisher = "Google";
    sha256 = "sha256-gJ7ghOOrk4kvzReqfB6ZRhFonOdpJXcPh7voBgCwqPg=";
    version = "0.20.0";
  },
  {
    name = "grafana-alloy";
    publisher = "grafana";
    sha256 = "sha256-XcoiEDCPp6GzYQDhJArZBEWxSnZrSTHofIyLFegsbh0=";
    version = "0.2.0";
  },
  {
    name = "grafana-vscode";
    publisher = "grafana";
    sha256 = "sha256-TpLOMwdaEdgzWVwUcn+fO4rgLiQammWQM8LQobt8gLw=";
    version = "0.0.19";
  },
  {
    name = "mypy-type-checker";
    publisher = "ms-python";
    sha256 = "sha256-CSiQWwpY/43Yx0/ppwq9f21ksqLYhr0Nv/i4+sno2Qs=";
    version = "2025.3.13521012";
  },
  {
    name = "pdf";
    publisher = "tomoki1207";
    sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    version = "1.2.2";
  },
  {
    name = "playwright";
    publisher = "ms-playwright";
    sha256 = "sha256-qIQS9rjzTJF0T6RWMJvaxOGcQmoXpIhzVHDMFxGMb/A=";
    version = "1.1.17";
  },
  {
    name = "prom";
    publisher = "ventura";
    sha256 = "sha256-h8pRrPzmu8+5ZiOLALjackr4zWuFAqi1ex7Gp2iOZKk=";
    version = "1.3.3";
  },
  {
    name = "pwc";
    publisher = "SureshNettur";
    sha256 = "sha256-e+O8mPGc50eJDvXMcLmsW7ht8jTXylbVoUf+ayaYx6E=";
    version = "1.2.1";
  },
  {
    name = "pyrefly";
    publisher = "meta";
    sha256 = "sha256-GSVas01jBL826ItyyKnWdYKAFYrIwIoKBLflfu9y8u0=";
    version = "0.50.0";
  },
  {
    name = "remotehub";
    publisher = "GitHub";
    sha256 = "sha256-+8W3jCfyJVtdLJxFhmmay5zefR+aqMtIaMIpMkzyKTs=";
    version = "0.65.2026012601";
  },
  {
    name = "ty";
    publisher = "astral-sh";
    sha256 = "sha256-cfIpCG8L8+Kf/Fka8CRU8gg8FgMO+TYRfdvMJ5J9h+Q=";
    version = "2026.8.0";
  },
  {
    name = "vscode-containers";
    publisher = "ms-azuretools";
    sha256 = "sha256-mGS1fppmcELhztvtnWQfW7MbtagQlVkbPtSaBHExzGA=";
    version = "2.4.0";
  },
  {
    name = "vscode-gitops-tools";
    publisher = "weaveworks";
    sha256 = "sha256-7MCKDnHCot/CL/SqZ2WuTxbqFdF75EC5WC+OxW0dcaE=";
    version = "0.27.0";
  },
  {
    name = "vscode-jsonnet";
    publisher = "grafana";
    sha256 = "sha256-Q8VzXzTdHo9h5+eCHHF1bPomPEbRsvouJcUfmFUDGMU=";
    version = "0.7.2";
  },
  {
    name = "vscode-pgsql";
    publisher = "ms-ossdata";
    sha256 = "sha256-/+VXsppHJlC+suEmu6d8lpryCKwfNWVA/nEYu4nhX3I=";
    version = "1.14.0";
  },
  {
    name = "vscode-python-test-adapter";
    publisher = "littlefoxteam";
    sha256 = "sha256-TwBPGr8bam1NSX2KRrm92DOQWeVa0k+pXT4q/isWYOI=";
    version = "0.8.2";
  },
  {
    name = "vscode-thunder-client";
    publisher = "rangav";
    sha256 = "sha256-8joP2BzTuUWS0XnpHonoClrfOw03pj2Bs+q9At7LtyI=";
    version = "2.38.6";
  }
]
