# -----------------------------------------------------
# Default Input Configuration
# Base settings that work for both desktop and laptop
# -----------------------------------------------------

input {
    # Keyboard layout
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    numlock_by_default = true

    # Mouse settings
    follow_mouse = 1
    mouse_refocus = false
    sensitivity = 0  # -1.0 to 1.0, 0 = no modification

}
