#!/usr/bin/env bash

if (($# == 0)); then
  echo "Usage: os-channel-set [stable|edge|dev]"
  exit 1
else
  channel="$1"
fi

case "$channel" in
"stable") os-branch-set "master" && os-refresh-pacman "stable" ;;
"edge") os-branch-set "master" && os-refresh-pacman "edge" ;;
"dev") os-branch-set "dev" && os-refresh-pacman "edge" ;;
*) echo "Unknown channel: $channel"; exit 1; ;;
esac

os-update -y
