#!/usr/bin/env bash

set -euo pipefail

if (($# == 0)); then
  echo "Usage: os-channel-set [stable|edge|dev]" >&2
  exit 1
fi

channel="$1"

case "$channel" in
  "stable")
    os-branch-set "master" && os-refresh-pacman "stable"
    ;;
  "edge")
    os-branch-set "master" && os-refresh-pacman "edge"
    ;;
  "dev")
    os-branch-set "dev" && os-refresh-pacman "edge"
    ;;
  *)
    echo "Unknown channel: $channel" >&2
    exit 1
    ;;
esac

os-update -y
