#!/usr/bin/env bash

os-cmd-present "$EDITOR" || EDITOR=nvim

case "$EDITOR" in
nvim | vim | nano | micro | hx | helix)
  exec os-launch-tui "$EDITOR" "$@"
  ;;
*)
  exec setsid uwsm-app -- "$EDITOR" "$@"
  ;;
esac
