name: Flake ❄️ Checker ✅

on:
  push:
    branches:
      - main
  schedule:
    # l33t o'clock
    - cron: '37 13 * * *'
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - uses: DeterminateSystems/flake-checker-action@v9
