.pragma library

var sectionKey = "launcher"

var maps = [
    ["defaultMode", "launcherDefaultMode"],
    ["showModeHints", "launcherShowModeHints"],
    ["showHomeSections", "launcherShowHomeSections"],
    ["drunCategoryFiltersEnabled", "launcherDrunCategoryFiltersEnabled"],
    ["enablePreload", "launcherEnablePreload"],
    ["keepSearchOnModeSwitch", "launcherKeepSearchOnModeSwitch"],
    ["enableDebugTimings", "launcherEnableDebugTimings"],
    ["showRuntimeMetrics", "launcherShowRuntimeMetrics"],
    ["characterTrigger", "launcherCharacterTrigger"],
    ["characterPasteOnSelect", "launcherCharacterPasteOnSelect"],
    ["preloadFailureThreshold", "launcherPreloadFailureThreshold"],
    ["preloadFailureBackoffSec", "launcherPreloadFailureBackoffSec"],
    ["maxResults", "launcherMaxResults"],
    ["fileMinQueryLength", "launcherFileMinQueryLength"],
    ["fileMaxResults", "launcherFileMaxResults"],
    ["fileSearchRoot", "launcherFileSearchRoot"],
    ["fileShowHidden", "launcherFileShowHidden"],
    ["fileOpener", "launcherFileOpener"],
    ["filePreviewEnabled", "launcherFilePreviewEnabled"],
    ["recentsLimit", "launcherRecentsLimit"],
    ["recentAppsLimit", "launcherRecentAppsLimit"],
    ["suggestionsLimit", "launcherSuggestionsLimit"],
    ["cacheTtlSec", "launcherCacheTtlSec"],
    ["searchDebounceMs", "launcherSearchDebounceMs"],
    ["fileSearchDebounceMs", "launcherFileSearchDebounceMs"],
    ["tabBehavior", "launcherTabBehavior"],
    ["webEnterUsesPrimary", "launcherWebEnterUsesPrimary"],
    ["webNumberHotkeysEnabled", "launcherWebNumberHotkeysEnabled"],
    ["webAliases", "launcherWebAliases"],
    ["rememberWebProvider", "launcherRememberWebProvider"],
    ["webLastProviderKey", "launcherWebLastProviderKey"],
    ["webProviderOrder", "launcherWebProviderOrder"],
    ["modeOrder", "launcherModeOrder"],
    ["enabledModes", "launcherEnabledModes"],
    ["primaryModes", "launcherPrimaryModes"],
    ["scoreNameWeight", "launcherScoreNameWeight"],
    ["scoreTitleWeight", "launcherScoreTitleWeight"],
    ["scoreExecWeight", "launcherScoreExecWeight"],
    ["scoreBodyWeight", "launcherScoreBodyWeight"],
    ["scoreCategoryWeight", "launcherScoreCategoryWeight"],
    ["webCustomEngines", "launcherWebCustomEngines"],
    ["webBangsEnabled", "launcherWebBangsEnabled"],
    ["webBangsLastSync", "launcherWebBangsLastSync"]
]
